/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas3;

import controladores3.controladorPresAdelanto;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class vistaPresAdelanto extends javax.swing.JDialog {

    /**
     * Creates new form vistaPresAdelanto
     */
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    String rut;
    
    public vistaPresAdelanto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoAnticipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoAdelanto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoPrestamo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinnerCuotas = new javax.swing.JSpinner();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        spinnerCuotasRes = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Anticipo");

        textoAnticipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoAnticipoFocusLost(evt);
            }
        });

        jLabel2.setText("Adelanto");

        textoAdelanto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoAdelantoFocusLost(evt);
            }
        });

        jLabel3.setText("Prestamo");

        textoPrestamo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoPrestamoFocusLost(evt);
            }
        });

        jLabel4.setText("Cuotas");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cuotas restantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerCuotas, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerCuotasRes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoAdelanto)
                            .addComponent(textoAnticipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoPrestamo))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAceptar, botonCancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoAdelanto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerCuotasRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(spinnerCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textoAnticipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoAnticipoFocusLost
        setTextoAnticipo(getTextoAnticipo());
    }//GEN-LAST:event_textoAnticipoFocusLost

    private void textoAdelantoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoAdelantoFocusLost
        setTextoAdelanto(getTextoAdelanto());
    }//GEN-LAST:event_textoAdelantoFocusLost

    private void textoPrestamoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoPrestamoFocusLost
        setTextoPrestamo(getTextoPrestamo());
    }//GEN-LAST:event_textoPrestamoFocusLost

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        controladores3.controladorPresAdelanto miControlador = new controladorPresAdelanto();
        if(miControlador.ingresarPresAdelanto()){
            JOptionPane.showMessageDialog(null, "Préstamo/Adelanto generado con éxito", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Error al generar préstamo/adelanto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPresAdelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPresAdelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPresAdelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPresAdelanto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaPresAdelanto dialog = new vistaPresAdelanto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spinnerCuotas;
    private javax.swing.JSpinner spinnerCuotasRes;
    private javax.swing.JTextField textoAdelanto;
    private javax.swing.JTextField textoAnticipo;
    private javax.swing.JTextField textoPrestamo;
    // End of variables declaration//GEN-END:variables

    public void setRut(String rut){
        this.rut = rut;
    }
    
    public String getRut(){
        return rut;
    }
    
    public String getSpinnerCuotas() {
        return spinnerCuotas.getValue().toString();
    }
    
    public String getSpinnerCuotasRes() {
        return spinnerCuotasRes.getValue().toString();
    }

    public void setSpinnerCuotas(String spinnerCuotas) {
        this.spinnerCuotas.setValue(new Integer(spinnerCuotas));
    }
    
    public void setSpinnerCuotasRes(String spinnerCuotasRes) {
        this.spinnerCuotasRes.setValue(new Integer(spinnerCuotasRes));
    }

    public String getTextoAdelanto() {
        if(textoAdelanto.getText().compareTo("") == 0){
            return "0";
        }
        String adelanto = textoAdelanto.getText();
        adelanto = adelanto.replace("$", "");
        adelanto = adelanto.replace(".", "");
        return adelanto;
    }

    public void setTextoAdelanto(String textoAdelanto) {
        try{
            Object value = Integer.parseInt(textoAdelanto);
            if (value instanceof Number) {
                this.textoAdelanto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoAdelanto.setText(FORMAT.format(value));
            } else {
                this.textoAdelanto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoAdelanto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoAdelanto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoAdelanto.setText("");
        }
    }

    public String getTextoAnticipo() {
        if(textoAnticipo.getText().compareTo("") == 0){
            return "0";
        }
        String anticipo = textoAnticipo.getText();
        anticipo = anticipo.replace("$", "");
        anticipo = anticipo.replace(".", "");
        return anticipo;
    }

    public void setTextoAnticipo(String textoAnticipo) {
        try{
            Object value = Integer.parseInt(textoAnticipo);
            if (value instanceof Number) {
                this.textoAnticipo.setHorizontalAlignment(JLabel.RIGHT);
                this.textoAnticipo.setText(FORMAT.format(value));
            } else {
                this.textoAnticipo.setHorizontalAlignment(JLabel.RIGHT);
                this.textoAnticipo.setText("");
            }
        }catch(NumberFormatException e){
            this.textoAnticipo.setHorizontalAlignment(JLabel.RIGHT);
            this.textoAnticipo.setText("");
        }
    }

    public String getTextoPrestamo() {
        if(textoPrestamo.getText().compareTo("") == 0){
            return "0";
        }
        String prestamo = textoPrestamo.getText();
        prestamo = prestamo.replace("$", "");
        prestamo = prestamo.replace(".", "");
        return prestamo;
    }

    public void setTextoPrestamo(String textoPrestamo) {
        try{
            Object value = Integer.parseInt(textoPrestamo);
            if (value instanceof Number) {
                this.textoPrestamo.setHorizontalAlignment(JLabel.RIGHT);
                this.textoPrestamo.setText(FORMAT.format(value));
            } else {
                this.textoPrestamo.setHorizontalAlignment(JLabel.RIGHT);
                this.textoPrestamo.setText("");
            }
        }catch(NumberFormatException e){
            this.textoPrestamo.setHorizontalAlignment(JLabel.RIGHT);
            this.textoPrestamo.setText("");
        }
    }
}
