/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas4;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author diego
 */
public class vistaIngresarTraspaletaOcs extends javax.swing.JDialog {

    String fechaInicio, fechaFin;
    String id;
    int nuevoNeto = 0;
    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formatClock = new SimpleDateFormat("HH:mm:ss");
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    DocumentFilter onlyNumbers = new DocumentFilter() {
            Pattern regEx = Pattern.compile("\\d+");

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                Matcher matcher = regEx.matcher(text);
                if (!matcher.matches()) {
                    return;
                }
                super.replace(fb, offset, length, text, attrs);
            }
        };
    /**
     * Creates new form vistaIngresarTraspaletaOcs
     */
    public vistaIngresarTraspaletaOcs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButton1.setVisible(false);
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
        ((AbstractDocument) textoCodigo.getDocument()).setDocumentFilter(onlyNumbers);
        textoDespacho.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        botonIngresar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoGiro = new javax.swing.JTextField();
        labelSeñores = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textoRazon2 = new javax.swing.JTextField();
        textoCodigo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        textoContacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoRazon = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        textoRutCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoDespacho = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textoNeto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textoBruto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textoIva = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textoDescuento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textoNuevoNeto = new javax.swing.JTextField();
        checkDespacho = new javax.swing.JCheckBox();
        textoCiudad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboCondPago = new javax.swing.JComboBox<>();
        textoDespachado = new javax.swing.JTextField();
        comboFormaPago = new javax.swing.JComboBox<>();
        textoFechaOt = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textoFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        textoFechaTermino = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spinnerTras = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar OC");

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Dirección");

        jLabel2.setText("Giro");

        textoGiro.setEditable(false);

        labelSeñores.setText("Señores");

        textoDireccion.setEditable(false);

        jLabel23.setText("Codigo Oc");

        textoRazon2.setEditable(false);

        jLabel22.setText("Observación en faena");

        textoObs.setEditable(false);
        textoObs.setColumns(20);
        textoObs.setLineWrap(true);
        textoObs.setRows(3);
        textoObs.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textoObs);

        jLabel3.setText("Solicitado por");

        jLabel7.setText("Trabajo realizado en");

        textoRazon.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCodigo)
                    .addComponent(textoRazon2)
                    .addComponent(textoDireccion)
                    .addComponent(textoGiro)
                    .addComponent(textoContacto)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSeñores)
                            .addComponent(jLabel1)
                            .addComponent(jLabel23)
                            .addComponent(jLabel2)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoRazon))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelSeñores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoRazon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addComponent(textoGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Rut");

        jLabel6.setText("Teléfono");

        textoTelefono.setEditable(false);

        textoRutCliente.setEditable(false);

        jLabel5.setText("Ciudad");

        textoDespacho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDespachoFocusLost(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        jLabel15.setText("Neto total");

        textoNeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoNetoFocusLost(evt);
            }
        });

        jLabel16.setText("Bruto");

        textoBruto.setEditable(false);

        jLabel17.setText("IVA");

        textoIva.setEditable(false);

        jLabel28.setText("Descuento");

        textoDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDescuentoFocusLost(evt);
            }
        });

        jLabel29.setText("Nuevo neto");

        textoNuevoNeto.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNuevoNeto)
                    .addComponent(textoDescuento)
                    .addComponent(textoNeto)
                    .addComponent(textoBruto)
                    .addComponent(textoIva)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textoNuevoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textoIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkDespacho.setText("Despacho");
        checkDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDespachoActionPerformed(evt);
            }
        });

        textoCiudad.setEditable(false);

        jLabel12.setText("Valor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoTelefono)
                    .addComponent(textoCiudad)
                    .addComponent(textoRutCliente)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(checkDespacho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDespacho)
                    .addComponent(jLabel12)
                    .addComponent(textoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Despachado por");

        jLabel8.setText("Fecha de OC");

        jLabel10.setText("Condición de pago");

        comboCondPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferencia", "Efectivo", "Cheque" }));

        comboFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al día", "30 días", "60 días", "90 días" }));

        jLabel9.setText("Forma de pago");

        jLabel13.setText("Fecha de inicio");

        textoFechaInicio.setEditable(false);

        textoFechaTermino.setEditable(false);

        jLabel14.setText("Fecha de término");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDespachado)
                    .addComponent(textoFechaOt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoFechaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCondPago, 0, 313, Short.MAX_VALUE)
                    .addComponent(comboFormaPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDespachado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCondPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel11.setText("Número de traspaletas");

        spinnerTras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        spinnerTras.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(botonIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerTras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(spinnerTras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresar)
                    .addComponent(botonCancelar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoDespachoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDespachoFocusLost
        setTextoValorDespacho(getTextoDespacho());
        setNuevoNeto(Integer.parseInt(getTextoNeto()) + Integer.parseInt(getTextoDespacho()) - Integer.parseInt(getTextoDescuento()));
        double nuevoIva = nuevoNeto * 0.19;
        double nuevoBruto = nuevoNeto + nuevoIva;
        setTextoIva(String.valueOf((int)nuevoIva));
        setTextoBruto(String.valueOf((int)nuevoBruto));
        setTextoNuevoNeto(String.valueOf(nuevoNeto));
    }//GEN-LAST:event_textoDespachoFocusLost

    private void textoNetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNetoFocusLost
        setTextoNeto(getTextoNeto());
        setNuevoNeto(Integer.parseInt(getTextoNeto()) - Integer.parseInt(getTextoDescuento()) + Integer.parseInt(getTextoDespacho()));
        double nuevoIva = nuevoNeto * 0.19;
        double nuevoBruto = nuevoNeto + nuevoIva;
        setTextoIva(String.valueOf((int)nuevoIva));
        setTextoBruto(String.valueOf((int)nuevoBruto));
        setTextoNuevoNeto(String.valueOf(nuevoNeto));
    }//GEN-LAST:event_textoNetoFocusLost

    private void textoDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDescuentoFocusLost
        setTextoDescuento(getTextoDescuento());
        setNuevoNeto(Integer.parseInt(getTextoNeto()) - Integer.parseInt(getTextoDescuento()) + Integer.parseInt(getTextoDespacho()));
        double nuevoIva = nuevoNeto * 0.19;
        double nuevoBruto = nuevoNeto + nuevoIva;
        setTextoIva(String.valueOf((int)nuevoIva));
        setTextoBruto(String.valueOf((int)nuevoBruto));
        setTextoNuevoNeto(String.valueOf(nuevoNeto));
    }//GEN-LAST:event_textoDescuentoFocusLost

    private void checkDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDespachoActionPerformed
        if(checkDespacho.isSelected()){
            textoDespacho.setEnabled(true);
        }else{
            textoDespacho.setEnabled(false);
        }
    }//GEN-LAST:event_checkDespachoActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        controladores4.controladorIngresarOcs miControladorIO = new controladores4.controladorIngresarOcs();
        String respuesta = miControladorIO.camposVacios2();
        boolean esVacio = respuesta.length() == 0;
        if(!esVacio){
            JOptionPane.showMessageDialog(this, respuesta, "Debe rellenar los siguientes campos", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(miControladorIO.irVistaJornadasTraspaletaOCP(id)){
                setVisible(false);
            }
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        System.out.println(tablaGruas.getModel().getValueAt(0, 6));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarTraspaletaOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarTraspaletaOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarTraspaletaOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarTraspaletaOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaIngresarTraspaletaOcs dialog = new vistaIngresarTraspaletaOcs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JCheckBox checkDespacho;
    private javax.swing.JComboBox<String> comboCondPago;
    private javax.swing.JComboBox<String> comboFormaPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSeñores;
    private javax.swing.JSpinner spinnerTras;
    private javax.swing.JTextField textoBruto;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoContacto;
    private javax.swing.JTextField textoDescuento;
    private javax.swing.JTextField textoDespachado;
    private javax.swing.JTextField textoDespacho;
    private javax.swing.JTextField textoDireccion;
    private org.jdesktop.swingx.JXDatePicker textoFechaInicio;
    private org.jdesktop.swingx.JXDatePicker textoFechaOt;
    private org.jdesktop.swingx.JXDatePicker textoFechaTermino;
    private javax.swing.JTextField textoGiro;
    private javax.swing.JTextField textoIva;
    private javax.swing.JTextField textoNeto;
    private javax.swing.JTextField textoNuevoNeto;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoRazon;
    private javax.swing.JTextField textoRazon2;
    private javax.swing.JTextField textoRutCliente;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables

    public String getTextoContacto() {
        return textoContacto.getText();
    }

    public String getTextoDireccion() {
        return textoDireccion.getText();
    }

    public String getTextoGiro() {
        return textoGiro.getText();
    }

    public String getTextoRazon() {
        return textoRazon.getText();
    }

    public String getTextoRutCliente() {
        return textoRutCliente.getText();
    }

    public String getTextoTelefono() {
        return textoTelefono.getText();
    }

    public String getTextoDespachado() {
        return textoDespachado.getText();
    }

    public String getTextoObs() {
        return textoObs.getText();
    }

    public String getComboCondPago() {
        return comboCondPago.getSelectedItem().toString();
    }

    public String getComboFormaPago() {
        return comboFormaPago.getSelectedItem().toString();
    }

    public String getTextoFechaOc() {
        Date fecha = textoFechaOt.getDate();
        if(fecha == null) return "";
        String dateString = formatDate.format(textoFechaOt.getDate());
        return dateString;
    }
    
    public int getMes(){
        Date fecha = textoFechaOt.getDate();
        Calendar cal = Calendar.getInstance();
        cal.setTime(fecha);
        System.out.println("Mes: " + cal.get(Calendar.MONTH));
        if(cal.get(Calendar.DAY_OF_MONTH) > 25)
            return cal.get(Calendar.MONTH) + 2;
        return cal.get(Calendar.MONTH) + 1;  
    }
    
    public int getYear(){
        Date fecha = textoFechaOt.getDate();
        Calendar cal = Calendar.getInstance();
        cal.setTime(fecha);
        System.out.println("Year: " + cal.get(Calendar.YEAR));
        return cal.get(Calendar.YEAR);  
    }

    public String getTextoCodigo() {
        return textoCodigo.getText();
    }

    public String getTextoBruto() {
        String bruto = textoBruto.getText();
        bruto = bruto.replace("$", "");
        bruto = bruto.replace(".", "");
        return bruto;
    }

    public String getTextoIva() {
        String iva = textoIva.getText();
        iva = iva.replace("$", "");
        iva = iva.replace(".", "");
        return iva;
    }

    public String getTextoNeto() {
        String neto = textoNeto.getText();
        neto = neto.replace("$", "");
        neto = neto.replace(".", "");
        return neto;
    }
    
    public String getTextoNuevoNeto() {
        String neto = textoNuevoNeto.getText();
        neto = neto.replace("$", "");
        neto = neto.replace(".", "");
        return neto;
    }

    public String getCheckDespacho() {
        if(checkDespacho.isSelected()) return "1";
        return "0";
    }

    public String getTextoDespacho() {
        if(getCheckDespacho().compareTo("0") == 0){
            return "0";
        }
        if(textoDespacho.getText().compareTo("") == 0){
            return "0";
        }else{
            String desp = textoDespacho.getText();
            desp = desp.replace("$", "");
            desp = desp.replace(".", "");
            return desp;
        }
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public void setTextoBruto(String textoBruto) {
        try{
            Object value = Integer.parseInt(textoBruto);
            if (value instanceof Number) {
                this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoBruto.setText(FORMAT.format(value));
            } else {
                this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoBruto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoBruto.setText("");
        }
    }
    
    public void setTextoNuevoNeto(String textoNuevoNeto) {
        try{
            Object value = Integer.parseInt(textoNuevoNeto);
            if (value instanceof Number) {
                this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNuevoNeto.setText(FORMAT.format(value));
            } else {
                this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNuevoNeto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoNuevoNeto.setText("");
        }
    }

    public void setTextoCiudad(String textoCiudad) {
        this.textoCiudad.setText(textoCiudad);
    }

    public void setTextoCodigo(String textoCodigo) {
        this.textoCodigo.setText(textoCodigo);
    }

    public void setTextoContacto(String textoContacto) {
        this.textoContacto.setText(textoContacto);
    }

    public void setTextoDespachado(String textoDespachado) {
        this.textoDespachado.setText(textoDespachado);
    }

    public void setTextoDespacho(String textoDespacho) {
        this.textoDespacho.setText(textoDespacho);
    }

    public void setTextoDireccion(String textoDireccion) {
        this.textoDireccion.setText(textoDireccion);
    }

    public void setTextoFechaOt() throws ParseException {
        this.textoFechaOt.setDate(new Date());
    }
    
    public void setTextoFechaInicio(String textoFechaInicio) throws ParseException {
        this.textoFechaInicio.setDate(formatDate.parse(textoFechaInicio));
    }
    
    public void setTextoFechaTermino(String textoFechaTermino) throws ParseException {
        this.textoFechaTermino.setDate(formatDate.parse(textoFechaTermino));
    }

    public void setTextoGiro(String textoGiro) {
        this.textoGiro.setText(textoGiro);
    }

    public void setTextoIva(String textoIva) {
        try{
            Object value = Integer.parseInt(textoIva);
            if (value instanceof Number) {
                this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
                this.textoIva.setText(FORMAT.format(value));
            } else {
                this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
                this.textoIva.setText("");
            }
        }catch(NumberFormatException e){
            this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
            this.textoIva.setText("");
        }
    }

    public void setTextoNeto(String textoNeto) {
        try{
            Object value = Integer.parseInt(textoNeto);
            if (value instanceof Number) {
                this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNeto.setText(FORMAT.format(value));
            } else {
                this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNeto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoNeto.setText("");
        }
    }

    public void setTextoObs(String textoObs) {
        this.textoObs.setText(textoObs);
    }

    public void setTextoRazon(String textoRazon) {
        this.textoRazon.setText(textoRazon);
    }

    public void setTextoRazon2(String textoRazon2) {
        this.textoRazon2.setText(textoRazon2);
    }

    public void setTextoRutCliente(String textoRutCliente) {
        this.textoRutCliente.setText(textoRutCliente);
    }

    public void setTextoTelefono(String textoTelefono) {
        this.textoTelefono.setText(textoTelefono);
    }
   
    public String getTextoDescuento() {
        String desc = textoDescuento.getText().replace("$", "");
        desc = desc.replace(".", "");
        return desc;
    }
    
    public void setTextoDescuento(String desc){
        try{
            Object value = Integer.parseInt(desc);
            if (value instanceof Number) {
                textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
                textoDescuento.setText(FORMAT.format(value));
            } else {
                textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
                textoDescuento.setText("");
                textoDescuento.setText(FORMAT.format(0));
            }
        }catch(NumberFormatException e){
            textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
            textoDescuento.setText("");
            textoDescuento.setText(FORMAT.format(0));
        }
    }
    
    public void setTextoValorDespacho(String valor){
        try{
            Object value = Integer.parseInt(valor);
            if (value instanceof Number) {
                textoDespacho.setHorizontalAlignment(JLabel.RIGHT);
                textoDespacho.setText(FORMAT.format(value));
            } else {
                textoDespacho.setHorizontalAlignment(JLabel.RIGHT);
                textoDespacho.setText("");
                textoDespacho.setText(FORMAT.format(0));
            }
        }catch(NumberFormatException e){
            textoDespacho.setHorizontalAlignment(JLabel.RIGHT);
            textoDespacho.setText("");
            textoDespacho.setText(FORMAT.format(0));
        }
    }
    
    public int getNuevoNeto(){
        return nuevoNeto;
    }
    
    public void setNuevoNeto(int neto){
        nuevoNeto = neto;
    }
    
    public void setNumTras(String numTras){
        spinnerTras.setValue(Integer.parseInt(numTras));
    }
}
