/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas4;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author diego
 */
public class vistaIngresarOcs extends javax.swing.JDialog {

    int horas = 0;
    String ton;
    String fechaInicio, fechaFin;
    String diaInicio, diaFin;
    String horaInicio, horaFin;
    String id;
    String rutEmp;
    int nuevoNeto = 0;
    MyTableModelGruas tg = new MyTableModelGruas();
    MyTableModelEmpleados te = new MyTableModelEmpleados();
    MyTableModelHoras th = new MyTableModelHoras();
    JComboBox comboTonelajes;
    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formatClock = new SimpleDateFormat("HH:mm:ss");
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    DocumentFilter onlyNumbers = new DocumentFilter() {
            Pattern regEx = Pattern.compile("\\d+");

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                Matcher matcher = regEx.matcher(text);
                if (!matcher.matches()) {
                    return;
                }
                super.replace(fb, offset, length, text, attrs);
            }
        };
    
    /**
     * Creates new form vistaIngresarOC
     */
    public vistaIngresarOcs(java.awt.Frame parent, boolean modal, Object[] dataTon) {
        super(parent, modal); 
        initComponents();
        jButton1.setVisible(false);
        comboTonelajes = new JComboBox<Object>(dataTon);
        tablaGruas.setModel(tg);
        tablaEmpleados.setModel(te);
        tablaHoras.setModel(th);
        tablaEmpleados.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor(comboTonelajes));
        TableColumnModel tcmGruas = tablaGruas.getColumnModel();
        TableColumnModel tcmEmp = tablaEmpleados.getColumnModel();
        tcmGruas.removeColumn(tcmGruas.getColumn(6));
        tcmEmp.removeColumn(tcmEmp.getColumn(11));
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
        ((AbstractDocument) textoCodigo.getDocument()).setDocumentFilter(onlyNumbers);
        textoDespacho.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoGiro = new javax.swing.JTextField();
        labelSeñores = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textoRazon2 = new javax.swing.JTextField();
        textoCodigo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        textoContacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoRazon = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        textoRutCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoDespacho = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textoNeto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textoBruto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textoIva = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textoDescuento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textoNuevoNeto = new javax.swing.JTextField();
        checkDespacho = new javax.swing.JCheckBox();
        textoCiudad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboCondPago = new javax.swing.JComboBox<>();
        textoDespachado = new javax.swing.JTextField();
        comboFormaPago = new javax.swing.JComboBox<>();
        textoFechaOt = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textoFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        textoFechaTermino = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaGruas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaHoras = new javax.swing.JTable();
        botonIngresar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar OC");

        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);

        jLabel1.setText("Dirección");

        jLabel2.setText("Giro");

        textoGiro.setEditable(false);

        labelSeñores.setText("Señores");

        textoDireccion.setEditable(false);

        jLabel23.setText("Codigo Oc");

        textoRazon2.setEditable(false);

        jLabel22.setText("Observación en faena");

        textoObs.setEditable(false);
        textoObs.setColumns(20);
        textoObs.setLineWrap(true);
        textoObs.setRows(3);
        textoObs.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textoObs);

        jLabel3.setText("Solicitado por");

        jLabel7.setText("Trabajo realizado en");

        textoRazon.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCodigo)
                    .addComponent(textoRazon2)
                    .addComponent(textoDireccion)
                    .addComponent(textoGiro)
                    .addComponent(textoContacto)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSeñores)
                            .addComponent(jLabel1)
                            .addComponent(jLabel23)
                            .addComponent(jLabel2)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(2, 2, 2))
                    .addComponent(textoRazon))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelSeñores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoRazon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addComponent(textoGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Rut");

        jLabel6.setText("Teléfono");

        textoTelefono.setEditable(false);

        textoRutCliente.setEditable(false);

        jLabel5.setText("Ciudad");

        textoDespacho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDespachoFocusLost(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        jLabel15.setText("Neto total");

        textoNeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoNetoFocusLost(evt);
            }
        });

        jLabel16.setText("Bruto");

        textoBruto.setEditable(false);

        jLabel17.setText("IVA");

        textoIva.setEditable(false);

        jLabel28.setText("Descuento");

        textoDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoDescuentoFocusLost(evt);
            }
        });

        jLabel29.setText("Nuevo neto");

        textoNuevoNeto.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNuevoNeto)
                    .addComponent(textoDescuento)
                    .addComponent(textoNeto)
                    .addComponent(textoBruto)
                    .addComponent(textoIva)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textoNuevoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textoIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkDespacho.setText("Despacho");
        checkDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDespachoActionPerformed(evt);
            }
        });

        textoCiudad.setEditable(false);

        jLabel12.setText("Valor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoTelefono)
                    .addComponent(textoCiudad)
                    .addComponent(textoRutCliente)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(checkDespacho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDespacho)
                    .addComponent(jLabel12)
                    .addComponent(textoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Despachado por");

        jLabel8.setText("Fecha de OC");

        jLabel10.setText("Condición de pago");

        comboCondPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferencia", "Efectivo", "Cheque" }));

        comboFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al día", "30 días", "60 días", "90 días" }));

        jLabel9.setText("Forma de pago");

        jLabel11.setText("Fecha de inicio");

        textoFechaInicio.setEditable(false);

        jLabel13.setText("Fecha de término");

        textoFechaTermino.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(textoFechaOt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoFechaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboFormaPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCondPago, 0, 303, Short.MAX_VALUE)
                    .addComponent(textoDespachado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDespachado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCondPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tablaGruas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGruas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaGruas);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tablaEmpleados);

        tablaHoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaHoras.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tablaHoras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel1);

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(787, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(botonIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(830, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresar)
                    .addComponent(botonCancelar)
                    .addComponent(jButton1))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addGap(54, 54, 54)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        controladores4.controladorIngresarOcs miControladorIO = new controladores4.controladorIngresarOcs();
        String respuesta = miControladorIO.camposVacios();
        boolean esVacio = respuesta.length() == 0;
        if(!esVacio){
            JOptionPane.showMessageDialog(this, respuesta, "Debe rellenar los siguientes campos", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(miControladorIO.irVistaJornadasOCP(id, horas)){
                setVisible(false);
                controladores4.controladorIngresarOcs micontroladorOcs = new controladores4.controladorIngresarOcs();
                micontroladorOcs.actualizarHoras(id);
                controladores.controladorGruas micontroladorGruas = new controladores.controladorGruas();
                controladores.controladorEmpleados micontroladorEmpleados = new controladores.controladorEmpleados();
                micontroladorOcs.actualizarHorometro();
                micontroladorOcs.agregarMensualidad(getMes(), getYear());
//                micontroladorEmpleados.agregarMensualidad(getRutEmp(), getMes(), getYear(), getHoras(), getSpinnerHorasExtraNormales(), getSpinnerHorasExtraFestivos(), getSpinnerColacion(), ton);
//                micontroladorEmpleados.agregarHoras(getRutEmp(), horas, ton);
//                micontroladorEmpleados.agregarColacion(getRutEmp(), getSpinnerColacion());
//                miControladorIO.agregarHorasExtra(id, getSpinnerHorasExtraNormales(), getSpinnerHorasExtraFestivos());
            }
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textoDespachoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDespachoFocusLost
        setTextoValorDespacho(getTextoDespacho());
        setNuevoNeto(Integer.parseInt(getTextoNeto()) + Integer.parseInt(getTextoDespacho()) - Integer.parseInt(getTextoDescuento()));
        double nuevoIva = nuevoNeto * 0.19;
        double nuevoBruto = nuevoNeto + nuevoIva;
        setTextoIva(String.valueOf((int)nuevoIva));
        setTextoBruto(String.valueOf((int)nuevoBruto));
        setTextoNuevoNeto(String.valueOf(nuevoNeto));
    }//GEN-LAST:event_textoDespachoFocusLost

    private void textoDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDescuentoFocusLost
        setTextoDescuento(getTextoDescuento());
        setNuevoNeto(Integer.parseInt(getTextoNeto()) - Integer.parseInt(getTextoDescuento()) + Integer.parseInt(getTextoDespacho()));
        double nuevoIva = nuevoNeto * 0.19;
        double nuevoBruto = nuevoNeto + nuevoIva;
        setTextoIva(String.valueOf((int)nuevoIva));
        setTextoBruto(String.valueOf((int)nuevoBruto));
        setTextoNuevoNeto(String.valueOf(nuevoNeto));
    }//GEN-LAST:event_textoDescuentoFocusLost

    private void checkDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDespachoActionPerformed
        if(checkDespacho.isSelected()){
            textoDespacho.setEnabled(true);
        }else{
            textoDespacho.setEnabled(false);
        }
    }//GEN-LAST:event_checkDespachoActionPerformed

    private void textoNetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoNetoFocusLost
        setTextoNeto(getTextoNeto());
        setNuevoNeto(Integer.parseInt(getTextoNeto()) - Integer.parseInt(getTextoDescuento()) + Integer.parseInt(getTextoDespacho()));
        double nuevoIva = nuevoNeto * 0.19;
        double nuevoBruto = nuevoNeto + nuevoIva;
        setTextoIva(String.valueOf((int)nuevoIva));
        setTextoBruto(String.valueOf((int)nuevoBruto));
        setTextoNuevoNeto(String.valueOf(nuevoNeto));
    }//GEN-LAST:event_textoNetoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(tablaGruas.getModel().getValueAt(0, 6));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JCheckBox checkDespacho;
    private javax.swing.JComboBox<String> comboCondPago;
    private javax.swing.JComboBox<String> comboFormaPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelSeñores;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaGruas;
    private javax.swing.JTable tablaHoras;
    private javax.swing.JTextField textoBruto;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoContacto;
    private javax.swing.JTextField textoDescuento;
    private javax.swing.JTextField textoDespachado;
    private javax.swing.JTextField textoDespacho;
    private javax.swing.JTextField textoDireccion;
    private org.jdesktop.swingx.JXDatePicker textoFechaInicio;
    private org.jdesktop.swingx.JXDatePicker textoFechaOt;
    private org.jdesktop.swingx.JXDatePicker textoFechaTermino;
    private javax.swing.JTextField textoGiro;
    private javax.swing.JTextField textoIva;
    private javax.swing.JTextField textoNeto;
    private javax.swing.JTextField textoNuevoNeto;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoRazon;
    private javax.swing.JTextField textoRazon2;
    private javax.swing.JTextField textoRutCliente;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables

    
    public String getTextoContacto() {
        return textoContacto.getText();
    }

    public String getTextoDireccion() {
        return textoDireccion.getText();
    }

    public String getTextoGiro() {
        return textoGiro.getText();
    }

    public String getTextoRazon() {
        return textoRazon.getText();
    }

    public String getTextoRutCliente() {
        return textoRutCliente.getText();
    }

    public String getTextoTelefono() {
        return textoTelefono.getText();
    }

    public String getTextoDespachado() {
        return textoDespachado.getText();
    }

    public String getTextoObs() {
        return textoObs.getText();
    }

    public String getComboCondPago() {
        return comboCondPago.getSelectedItem().toString();
    }

    public String getComboFormaPago() {
        return comboFormaPago.getSelectedItem().toString();
    }

    public String getTextoFechaOc() {
        Date fecha = textoFechaOt.getDate();
        if(fecha == null) return "";
        String dateString = formatDate.format(textoFechaOt.getDate());
        return dateString;
    }
    
    public int getMes(){
        Date fecha = textoFechaOt.getDate();
        Calendar cal = Calendar.getInstance();
        cal.setTime(fecha);
        System.out.println("Mes: " + cal.get(Calendar.MONTH));
        if(cal.get(Calendar.DAY_OF_MONTH) > 25)
            return cal.get(Calendar.MONTH) + 2;
        return cal.get(Calendar.MONTH) + 1;  
    }
    
    public int getYear(){
        Date fecha = textoFechaOt.getDate();
        Calendar cal = Calendar.getInstance();
        cal.setTime(fecha);
        System.out.println("Year: " + cal.get(Calendar.YEAR));
        return cal.get(Calendar.YEAR);  
    }

    public String getTextoCodigo() {
        return textoCodigo.getText();
    }

    public String getTextoBruto() {
        String bruto = textoBruto.getText();
        bruto = bruto.replace("$", "");
        bruto = bruto.replace(".", "");
        return bruto;
    }

    public String getTextoIva() {
        String iva = textoIva.getText();
        iva = iva.replace("$", "");
        iva = iva.replace(".", "");
        return iva;
    }

    public String getTextoNeto() {
        String neto = textoNeto.getText();
        neto = neto.replace("$", "");
        neto = neto.replace(".", "");
        return neto;
    }
    
    public String getTextoNuevoNeto() {
        String neto = textoNuevoNeto.getText();
        neto = neto.replace("$", "");
        neto = neto.replace(".", "");
        return neto;
    }

//    public void setHoras(int horas){
//        this.horas = horas;
//    }
//    
//    public int getHoras(){
//        return this.horas;
//    }
    public String getCheckDespacho() {
        if(checkDespacho.isSelected()) return "1";
        return "0";
    }
//    
//    public int getSpinnerColacion(){
//        int colacion = 2 * (Integer) spinnerCol1.getValue() + (Integer) spinnerCol30.getValue();
//        return colacion;
//    }
//    
//    //Horas extra totales
//    /***BORRAR***/
//    public double getSpinnerHorasExtra(){
//        double horasEx = (Double) spinnerHoraExNormales.getValue() + (Double) spinnerHoraExFes.getValue();
//        return horasEx;
//    }
//    
//    
//    public double getSpinnerHorasExtraNormales(){
//        double horasEx = (Double) spinnerHoraExNormales.getValue();
//        return horasEx;
//    }
//    
//    public double getSpinnerHorasExtraFestivos(){
//        double horasEx = (Double) spinnerHoraExFes.getValue();
//        return horasEx;
//    }
//    
//    /***BORRAR***/
//    //Horas para el calculo // HoraEx al 50% = 1, al 100% = 2
//    public double getHorasExCal(){
//        double horasEx =  (Double) spinnerHoraExNormales.getValue() + 2 * (Double) spinnerHoraExFes.getValue();
//        return horasEx;
//    }
//
    public String getTextoDespacho() {
        if(getCheckDespacho().compareTo("0") == 0){
            return "0";
        }
        if(textoDespacho.getText().compareTo("") == 0){
            return "0";
        }else{
            String desp = textoDespacho.getText();
            desp = desp.replace("$", "");
            desp = desp.replace(".", "");
            return desp;
        }
    }
//
//    public void setTon(String ton) {
//        this.ton = ton;
//    }
//
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    public void setDiaInicio(String diaInicio) {
        this.diaInicio = diaInicio;
    }

    public void setDiaFin(String diaFin) {
        this.diaFin = diaFin;
    }

    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }

    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public void setTextoBruto(String textoBruto) {
        try{
            Object value = Integer.parseInt(textoBruto);
            if (value instanceof Number) {
                this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoBruto.setText(FORMAT.format(value));
            } else {
                this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoBruto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoBruto.setText("");
        }
    }
    
    public void setTextoNuevoNeto(String textoNuevoNeto) {
        try{
            Object value = Integer.parseInt(textoNuevoNeto);
            if (value instanceof Number) {
                this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNuevoNeto.setText(FORMAT.format(value));
            } else {
                this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNuevoNeto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoNuevoNeto.setText("");
        }
    }

    public void setTextoCiudad(String textoCiudad) {
        this.textoCiudad.setText(textoCiudad);
    }

    public void setTextoCodigo(String textoCodigo) {
        this.textoCodigo.setText(textoCodigo);
    }

    public void setTextoContacto(String textoContacto) {
        this.textoContacto.setText(textoContacto);
    }

    public void setTextoDespachado(String textoDespachado) {
        this.textoDespachado.setText(textoDespachado);
    }

    public void setTextoDespacho(String textoDespacho) {
        this.textoDespacho.setText(textoDespacho);
    }

    public void setTextoDireccion(String textoDireccion) {
        this.textoDireccion.setText(textoDireccion);
    }

    public void setTextoFechaOt() throws ParseException {
        this.textoFechaOt.setDate(new Date());
    }
    
    public void setTextoFechaInicio(String textoFechaInicio) throws ParseException {
        this.textoFechaInicio.setDate(formatDate.parse(textoFechaInicio));
    }
    
    public void setTextoFechaTermino(String textoFechaTermino) throws ParseException {
        this.textoFechaTermino.setDate(formatDate.parse(textoFechaTermino));
    }

    public void setTextoGiro(String textoGiro) {
        this.textoGiro.setText(textoGiro);
    }

    public void setTextoIva(String textoIva) {
        try{
            Object value = Integer.parseInt(textoIva);
            if (value instanceof Number) {
                this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
                this.textoIva.setText(FORMAT.format(value));
            } else {
                this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
                this.textoIva.setText("");
            }
        }catch(NumberFormatException e){
            this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
            this.textoIva.setText("");
        }
    }

    public void setTextoNeto(String textoNeto) {
        try{
            Object value = Integer.parseInt(textoNeto);
            if (value instanceof Number) {
                this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNeto.setText(FORMAT.format(value));
            } else {
                this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNeto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoNeto.setText("");
        }
    }

    public void setTextoObs(String textoObs) {
        this.textoObs.setText(textoObs);
    }

    public void setTextoRazon(String textoRazon) {
        this.textoRazon.setText(textoRazon);
    }

    public void setTextoRazon2(String textoRazon2) {
        this.textoRazon2.setText(textoRazon2);
    }

    public void setTextoRutCliente(String textoRutCliente) {
        this.textoRutCliente.setText(textoRutCliente);
    }

    public void setTextoTelefono(String textoTelefono) {
        this.textoTelefono.setText(textoTelefono);
    }
   
    public String getTextoDescuento() {
        String desc = textoDescuento.getText().replace("$", "");
        desc = desc.replace(".", "");
        return desc;
    }
    
    public void setTextoDescuento(String desc){
        try{
            Object value = Integer.parseInt(desc);
            if (value instanceof Number) {
                textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
                textoDescuento.setText(FORMAT.format(value));
            } else {
                textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
                textoDescuento.setText("");
                textoDescuento.setText(FORMAT.format(0));
            }
        }catch(NumberFormatException e){
            textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
            textoDescuento.setText("");
            textoDescuento.setText(FORMAT.format(0));
        }
    }
    
    public void setTextoValorDespacho(String valor){
        try{
            Object value = Integer.parseInt(valor);
            if (value instanceof Number) {
                textoDespacho.setHorizontalAlignment(JLabel.RIGHT);
                textoDespacho.setText(FORMAT.format(value));
            } else {
                textoDespacho.setHorizontalAlignment(JLabel.RIGHT);
                textoDespacho.setText("");
                textoDespacho.setText(FORMAT.format(0));
            }
        }catch(NumberFormatException e){
            textoDespacho.setHorizontalAlignment(JLabel.RIGHT);
            textoDespacho.setText("");
            textoDespacho.setText(FORMAT.format(0));
        }
    }
    
    public int getNuevoNeto(){
        return nuevoNeto;
    }
    
    public void setNuevoNeto(int neto){
        nuevoNeto = neto;
    }
    
    public JTable getTablaGruas() {
        return tablaGruas;
    }
    
    public JTable getTablaEmpleados() {
        return tablaEmpleados;
    }
    
    public JTable getTablaHoras() {
        return tablaHoras;
    }
    
    public void agregarGruas(String id) throws ParseException{
        int i = 0;
        modelos4.modeloJornadasOC detalle_gru = new modelos4.modeloJornadasOC();
        Object[][] data = detalle_gru.obtenerGruasPorIdJornadaOC(id);
        tg.setRowCount(data.length);
        for(Object[] data1 : data){
            tablaGruas.setValueAt(data1[0], i, 0);
            tablaGruas.setValueAt(data1[1], i, 1);
            tablaGruas.setValueAt(data1[2], i, 2);
            tablaGruas.setValueAt(data1[3], i, 3);
            tablaGruas.setValueAt(data1[4], i, 4);
            tablaGruas.setValueAt(0, i, 5);
            tablaGruas.getModel().setValueAt(data1[5], i, 6);
            i++;
        }
    }
    
    public void agregarEmpleados(String id) throws ParseException{
        int i = 0;
        modelos4.modeloJornadasOC detalle_emp = new modelos4.modeloJornadasOC();
        Object[][] data = detalle_emp.obtenerEmpleadosPorIdJornadaOC(id);
        te.setRowCount(data.length);
        for(Object[] data1 : data){
            tablaEmpleados.setValueAt(data1[0], i, 0);
            tablaEmpleados.setValueAt(data1[1], i, 1);
            tablaEmpleados.setValueAt(data1[2], i, 2);
            tablaEmpleados.setValueAt(data1[3], i, 3);
            tablaEmpleados.setValueAt(data1[4], i, 4);
            tablaEmpleados.setValueAt(0, i, 5);
            tablaEmpleados.setValueAt(0, i, 6);
            tablaEmpleados.setValueAt(0, i, 7);
            tablaEmpleados.setValueAt(0, i, 8);
            tablaEmpleados.setValueAt(0, i, 9);
            tablaEmpleados.getModel().setValueAt(data1[5], i, 11);
            i++;
        }
    }
    
    public void agregarHoras(String id) throws ParseException{
        int i = 0;
        modelos4.modeloJornadasOC detalle_horas = new modelos4.modeloJornadasOC();
        String[][] data = detalle_horas.obtenerHorasPorIdJornadaOC(id);
        th.setRowCount(data.length);
        for(String[] data1 : data){
            tablaHoras.setValueAt(Double.parseDouble(data1[0]), i, 0);
            tablaHoras.setValueAt(Double.parseDouble(data1[1]), i, 1);
            tablaHoras.setValueAt(Double.parseDouble(data1[2]), i, 2);
            tablaHoras.setValueAt(Double.parseDouble(data1[3]), i, 3);
            tablaHoras.setValueAt(0, i, 4);
            tablaHoras.setValueAt(0, i, 5);
            tablaHoras.setValueAt(0, i, 6);
            tablaHoras.setValueAt(0, i, 7);
            i++;
        }
    }

    public String getHorasEmpleadosVacia() {
        for (int i = 0; i < tablaEmpleados.getRowCount(); i++) {
                if ((double)tablaEmpleados.getValueAt(i, 5) == 0.0) {
                    System.out.println(tablaEmpleados.getValueAt(i, 5));
                    return "";
            }
        }
        return "novacio";
    }
    
    public class MyTableModelGruas extends DefaultTableModel{
        public MyTableModelGruas() {
          super(new String[]{"Grua", "Fecha de salida", "Hora de salida", "Fecha de regreso", "Hora de regreso", "Horas totales", "Id"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
              case 5:
                  return Double.class;
            default:
                return String.class;
          }
        }
        
        @Override
        public Object getValueAt(int row, int col){
            return super.getValueAt(row, col);
        }
        
        @Override 
        public boolean isCellEditable(int row, int col){
            if(col == 5) return true;
            return false;
        }
    }
    
    public class MyTableModelEmpleados extends DefaultTableModel{
        public MyTableModelEmpleados() {
          super(new String[]{"Empleado", "Fecha de salida", "Hora de salida", "Fecha de regreso", "Hora de regreso", "Horas totales", "Horas extra nor.", 
              "Horas extra fes.", "Días media colación", "Días sin colación", "Ton. empleado", "Id"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
              case 5:
                  return Double.class;
              case 6:
                  return Double.class;
              case 7:
                  return Double.class;
              case 8:
                  return Integer.class;
              case 9:
                  return Integer.class;
            default:
                return String.class;
          }
        }
        
        @Override
        public Object getValueAt(int row, int col){
            if(col == 10 && super.getValueAt(row, col) == null){
                return 3;
            }
            return super.getValueAt(row, col);
        }
        
        @Override 
        public boolean isCellEditable(int row, int col){
            if(col > 4) return true;
            return false;
        }
    }
    
    public class MyTableModelHoras extends DefaultTableModel {

        public MyTableModelHoras() {
            super(new String[]{"Tonelajes", "N° de horas", "N° de Turnos", "Horas base", "Valor", "Horas ad.", "Horas extra", "Turnos ex."}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
            switch (column) {
                default:
                    return Double.class;
            }
        }

        @Override
        public Object getValueAt(int row, int col) {
            if (super.getValueAt(row, col) == null) {
                return 0.0;
            }
            return super.getValueAt(row, col);
        }
        
        @Override
        public boolean isCellEditable(int row, int col){
            if(col > 3) return true;
            return false;
        }
        
//        @Override
//        public void setValueAt(Object value, int row, int column){
//            super.setValueAt(value, row, column);
//            double nextValue = (Double)getValueAt(row,1) * (Double)getValueAt(row, 2) ;
//            System.out.println(nextValue);
//            super.setValueAt(nextValue, row, 3);
//            
//        }
    }
}
