/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas4;

import java.awt.Color;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class vistaDetalleOcs extends javax.swing.JDialog {

    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-ddd");
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    MyTableModelGruas tg = new MyTableModelGruas();
    MyTableModelEmpleados te = new MyTableModelEmpleados();
    MyTableModelHoras th = new MyTableModelHoras();
    /**
     * Creates new form vistaDetalleOC
     */
    public vistaDetalleOcs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
        tablaGruas.setModel(tg);
        tablaEmpleados.setModel(te);
        tablaHoras.setModel(th);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoGiro = new javax.swing.JTextField();
        labelSeñores = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textoRazon2 = new javax.swing.JTextField();
        textoCodigo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        textoContacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoRazon = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        textoRutCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoDespacho = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textoNeto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textoBruto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textoIva = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textoDescuento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textoNuevoNeto = new javax.swing.JTextField();
        checkDespacho = new javax.swing.JCheckBox();
        textoCiudad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboCondPago = new javax.swing.JComboBox<>();
        textoDespachado = new javax.swing.JTextField();
        comboFormaPago = new javax.swing.JComboBox<>();
        textoFechaOc = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textoFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        textoFechaTermino = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaGruas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaHoras = new javax.swing.JTable();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle OC");

        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);

        jLabel1.setText("Dirección");

        jLabel2.setText("Giro");

        textoGiro.setEditable(false);

        labelSeñores.setText("Señores");

        textoDireccion.setEditable(false);

        jLabel23.setText("Codigo Oc");

        textoRazon2.setEditable(false);

        textoCodigo.setEditable(false);

        jLabel22.setText("Observación en faena");

        textoObs.setEditable(false);
        textoObs.setColumns(20);
        textoObs.setLineWrap(true);
        textoObs.setRows(3);
        textoObs.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textoObs);

        textoContacto.setEditable(false);

        jLabel3.setText("Solicitado por");

        jLabel7.setText("Trabajo realizado en");

        textoRazon.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCodigo)
                    .addComponent(textoRazon2)
                    .addComponent(textoDireccion)
                    .addComponent(textoGiro)
                    .addComponent(textoContacto)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSeñores)
                            .addComponent(jLabel1)
                            .addComponent(jLabel23)
                            .addComponent(jLabel2)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoRazon))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelSeñores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoRazon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addComponent(textoGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Rut");

        jLabel6.setText("Teléfono");

        textoTelefono.setEditable(false);

        textoRutCliente.setEditable(false);

        jLabel5.setText("Ciudad");

        textoDespacho.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        jLabel15.setText("Neto total");

        textoNeto.setEditable(false);

        jLabel16.setText("Bruto");

        textoBruto.setEditable(false);

        jLabel17.setText("IVA");

        textoIva.setEditable(false);

        jLabel28.setText("Descuento");

        textoDescuento.setEditable(false);

        jLabel29.setText("Nuevo neto");

        textoNuevoNeto.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNuevoNeto)
                    .addComponent(textoDescuento)
                    .addComponent(textoNeto)
                    .addComponent(textoBruto)
                    .addComponent(textoIva)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(textoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textoNuevoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textoIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkDespacho.setText("Despacho");
        checkDespacho.setEnabled(false);
        checkDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDespachoActionPerformed(evt);
            }
        });

        textoCiudad.setEditable(false);

        jLabel12.setText("Valor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoTelefono)
                    .addComponent(textoCiudad)
                    .addComponent(textoRutCliente)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(checkDespacho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDespacho)
                    .addComponent(jLabel12)
                    .addComponent(textoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Despachado por");

        jLabel8.setText("Fecha de OC");

        jLabel10.setText("Condición de pago");

        comboCondPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferencia", "Efectivo", "Cheque" }));
        comboCondPago.setEnabled(false);

        textoDespachado.setEditable(false);

        comboFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al día", "30 días", "60 días", "90 días" }));
        comboFormaPago.setEnabled(false);

        textoFechaOc.setEditable(false);

        jLabel9.setText("Forma de pago");

        jLabel11.setText("Fecha de inicio");

        textoFechaInicio.setEditable(false);

        jLabel13.setText("Fecha de término");

        textoFechaTermino.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoDespachado)
                    .addComponent(comboCondPago, 0, 239, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(textoFechaOc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboFormaPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(textoFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(textoFechaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDespachado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaOc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCondPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tablaGruas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGruas.setDragEnabled(true);
        tablaGruas.setEnabled(false);
        jScrollPane3.setViewportView(tablaGruas);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleados.setEnabled(false);
        jScrollPane4.setViewportView(tablaEmpleados);

        tablaHoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaHoras.setEnabled(false);
        jScrollPane5.setViewportView(tablaHoras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonCancelar.setText("OK");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDespachoActionPerformed
        if(checkDespacho.isSelected()){
            textoDespacho.setEnabled(true);
        }else{
            textoDespacho.setEnabled(false);
        }
    }//GEN-LAST:event_checkDespachoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleOcs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaDetalleOcs dialog = new vistaDetalleOcs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JCheckBox checkDespacho;
    private javax.swing.JComboBox<String> comboCondPago;
    private javax.swing.JComboBox<String> comboFormaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelSeñores;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaGruas;
    private javax.swing.JTable tablaHoras;
    private javax.swing.JTextField textoBruto;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoContacto;
    private javax.swing.JTextField textoDescuento;
    private javax.swing.JTextField textoDespachado;
    private javax.swing.JTextField textoDespacho;
    private javax.swing.JTextField textoDireccion;
    private org.jdesktop.swingx.JXDatePicker textoFechaInicio;
    private org.jdesktop.swingx.JXDatePicker textoFechaOc;
    private org.jdesktop.swingx.JXDatePicker textoFechaTermino;
    private javax.swing.JTextField textoGiro;
    private javax.swing.JTextField textoIva;
    private javax.swing.JTextField textoNeto;
    private javax.swing.JTextField textoNuevoNeto;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoRazon;
    private javax.swing.JTextField textoRazon2;
    private javax.swing.JTextField textoRutCliente;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables

//    public void setDiaInicio(String diaInicio) {
//        this.diaInicio = diaInicio;
//    }
//
//    public void setDiaFin(String diaFin) {
//        this.diaFin = diaFin;
//    }
//
//    public void setHoraInicio(String horaInicio) {
//        this.horaInicio = horaInicio;
//    }
//
//    public void setHoraFin(String horaFin) {
//        this.horaFin = horaFin;
//    }
//
//    public void setId(String id) {
//        this.id = id;
//    }
    
    public void setTextoBruto(String textoBruto) {
        try{
            Object value = Integer.parseInt(textoBruto);
            if (value instanceof Number) {
                this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoBruto.setText(FORMAT.format(value));
            } else {
                this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoBruto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoBruto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoBruto.setText("");
        }
    }
    
    public void setTextoNuevoNeto(String textoNuevoNeto) {
        try{
            Object value = Integer.parseInt(textoNuevoNeto);
            if (value instanceof Number) {
                this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNuevoNeto.setText(FORMAT.format(value));
            } else {
                this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNuevoNeto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoNuevoNeto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoNuevoNeto.setText("");
        }
    }

    public void setTextoCiudad(String textoCiudad) {
        this.textoCiudad.setText(textoCiudad);
    }

    public void setTextoCodigo(String textoCodigo) {
        this.textoCodigo.setText(textoCodigo);
    }

    public void setTextoContacto(String textoContacto) {
        this.textoContacto.setText(textoContacto);
    }

    public void setTextoDespachado(String textoDespachado) {
        this.textoDespachado.setText(textoDespachado);
    }

    public void setTextoDespacho(String textoDespacho) {
        this.textoDespacho.setText(textoDespacho);
    }

    public void setTextoDireccion(String textoDireccion) {
        this.textoDireccion.setText(textoDireccion);
    }
    
    public void setTextoFechaOc(String textoFechaOc) throws ParseException {
        this.textoFechaOc.setDate(formatDate.parse(textoFechaOc));
    }
    
    public void setTextoFechaInicio(String textoFechaInicio) throws ParseException {
        this.textoFechaInicio.setDate(formatDate.parse(textoFechaInicio));
    }
    
    public void setTextoFechaTermino(String textoFechaTermino) throws ParseException {
        this.textoFechaTermino.setDate(formatDate.parse(textoFechaTermino));
    }

    public void setTextoGiro(String textoGiro) {
        this.textoGiro.setText(textoGiro);
    }

    public void setTextoIva(String textoIva) {
        try{
            Object value = Integer.parseInt(textoIva);
            if (value instanceof Number) {
                this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
                this.textoIva.setText(FORMAT.format(value));
            } else {
                this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
                this.textoIva.setText("");
            }
        }catch(NumberFormatException e){
            this.textoIva.setHorizontalAlignment(JLabel.RIGHT);
            this.textoIva.setText("");
        }
    }

    public void setTextoNeto(String textoNeto) {
        try{
            Object value = Integer.parseInt(textoNeto);
            if (value instanceof Number) {
                this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNeto.setText(FORMAT.format(value));
            } else {
                this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
                this.textoNeto.setText("");
            }
        }catch(NumberFormatException e){
            this.textoNeto.setHorizontalAlignment(JLabel.RIGHT);
            this.textoNeto.setText("");
        }
    }
    
    public void setTextoDescuento(String textoDescuento) {
        try{
            Object value = Integer.parseInt(textoDescuento);
            if (value instanceof Number) {
                this.textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
                this.textoDescuento.setText(FORMAT.format(value));
            } else {
                this.textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
                this.textoDescuento.setText("");
            }
        }catch(NumberFormatException e){
            this.textoDescuento.setHorizontalAlignment(JLabel.RIGHT);
            this.textoDescuento.setText("");
        }
    }

    public void setTextoObs(String textoObs) {
        this.textoObs.setText(textoObs);
    }

    public void setTextoRazon(String textoRazon) {
        this.textoRazon.setText(textoRazon);
    }

    public void setTextoRazon2(String textoRazon2) {
        this.textoRazon2.setText(textoRazon2);
    }

    public void setTextoRutCliente(String textoRutCliente) {
        this.textoRutCliente.setText(textoRutCliente);
    }

    public void setTextoTelefono(String textoTelefono) {
        this.textoTelefono.setText(textoTelefono);
    }
    
    public void setComboCondPago(String comboCondPago) {
        this.comboCondPago.setSelectedItem(comboCondPago);
        ((JTextField)this.comboCondPago.getEditor().getEditorComponent()).setDisabledTextColor(Color.black);
    }
    
    public void setComboFormaPago(String comboFormaPago) {
        this.comboFormaPago.setSelectedItem(comboFormaPago);
        ((JTextField)this.comboFormaPago.getEditor().getEditorComponent()).setDisabledTextColor(Color.black);
    }
    
    public void setCheckDespacho(String checkDespacho) {
        if(checkDespacho.compareTo("1") == 0){
            this.checkDespacho.setSelected(true);
        }else{
            this.checkDespacho.setSelected(false);
        }
    }
    
    public void agregarGruas(String[][] data) throws ParseException{
        int i = 0;
        tg.setRowCount(data.length);
        for(Object[] data1 : data){
            tablaGruas.setValueAt(data1[0], i, 0);
            tablaGruas.setValueAt(data1[1], i, 1);
            tablaGruas.setValueAt(data1[2], i, 2);
            tablaGruas.setValueAt(data1[3], i, 3);
            tablaGruas.setValueAt(data1[4], i, 4);
            tablaGruas.setValueAt(Double.parseDouble(data1[6].toString()), i, 5);
            i++;
        }
    }
    
    public void agregarEmpleados(String[][] data) throws ParseException{
        int i = 0;
        te.setRowCount(data.length);
        for(Object[] data1 : data){
            tablaEmpleados.setValueAt(data1[0], i, 0);
            tablaEmpleados.setValueAt(data1[1], i, 1);
            tablaEmpleados.setValueAt(data1[2], i, 2);
            tablaEmpleados.setValueAt(data1[3], i, 3);
            tablaEmpleados.setValueAt(data1[4], i, 4);
            tablaEmpleados.setValueAt(Double.parseDouble(data1[6].toString()), i, 5);
            tablaEmpleados.setValueAt(Double.parseDouble(data1[7].toString()), i, 6);
            tablaEmpleados.setValueAt(Double.parseDouble(data1[8].toString()), i, 7);
            tablaEmpleados.setValueAt(Integer.parseInt(data1[9].toString()), i, 8);
            tablaEmpleados.setValueAt(Integer.parseInt(data1[10].toString()), i, 9);
            tablaEmpleados.setValueAt(data1[11], i, 10);
            i++;
        }
    }
    
    public void agregarHoras(String[][] data) throws ParseException{
        int i = 0;
        th.setRowCount(data.length);
        for(String[] data1 : data){
            tablaHoras.setValueAt(Double.parseDouble(data1[0]), i, 0);
            tablaHoras.setValueAt(Double.parseDouble(data1[1]), i, 1);
            tablaHoras.setValueAt(Double.parseDouble(data1[2]), i, 2);
            tablaHoras.setValueAt(Double.parseDouble(data1[3]), i, 3);
            tablaHoras.setValueAt(Double.parseDouble(data1[4]), i, 4);
            tablaHoras.setValueAt(Double.parseDouble(data1[5]), i, 5);
            tablaHoras.setValueAt(Double.parseDouble(data1[6]), i, 6);
            tablaHoras.setValueAt(Double.parseDouble(data1[7]), i, 7);
            i++;
        }
    }
    
    public class MyTableModelGruas extends DefaultTableModel{
        public MyTableModelGruas() {
          super(new String[]{"Grua", "Fecha de salida", "Hora de salida", "Fecha de regreso", "Hora de regreso", "Horas totales"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
              case 5:
                  return Double.class;
            default:
                return String.class;
          }
        }
        
        @Override
        public Object getValueAt(int row, int col){
            return super.getValueAt(row, col);
        }
        
        @Override 
        public boolean isCellEditable(int row, int col){
            if(col == 5) return true;
            return false;
        }
    }
    
    public class MyTableModelEmpleados extends DefaultTableModel{
        public MyTableModelEmpleados() {
          super(new String[]{"Empleado", "Fecha de salida", "Hora de salida", "Fecha de regreso", "Hora de regreso", "Horas totales", "Horas extra nor.", "Horas extra fes.", "Días media colación", "Días sin colación", "Tonelaje"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
              case 5:
                  return Double.class;
              case 6:
                  return Double.class;
              case 7:
                  return Double.class;
              case 8:
                  return Integer.class;
              case 9:
                  return Integer.class;
            default:
                return String.class;
          }
        }
        
        @Override
        public Object getValueAt(int row, int col){
            return super.getValueAt(row, col);
        }
        
        @Override 
        public boolean isCellEditable(int row, int col){
            if(col > 4) return true;
            return false;
        }
    }
    
    public class MyTableModelHoras extends DefaultTableModel {

        public MyTableModelHoras() {
            super(new String[]{"Tonelajes", "N° de horas", "N° de Turnos", "Horas base", "Valor", "Horas ad.", "Horas extra", "Turnos ex."}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
            switch (column) {
                default:
                    return Double.class;
            }
        }

        @Override
        public Object getValueAt(int row, int col) {
            if (super.getValueAt(row, col) == null) {
                return 0.0;
            }
            return super.getValueAt(row, col);
        }
        
        @Override
        public boolean isCellEditable(int row, int col){
            if(col > 3) return true;
            return false;
        }
    }
}
