/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.controladorIngresarEmpleados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author diego
 */
public class vistaIngresarEmpleados extends javax.swing.JDialog {

    DocumentFilter onlyNumbers = new DocumentFilter() {
            Pattern regEx = Pattern.compile("\\d+");

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                Matcher matcher = regEx.matcher(text);
                if (!matcher.matches()) {
                    return;
                }
                super.replace(fb, offset, length, text, attrs);
            }
        };
    
//    DocumentFilter numbersComma = new DocumentFilter() {
//            Pattern regEx = Pattern.compile("^[0-9]*\\,[0-9]*|[0-9]+$");
//            
//            @Override
//            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
//                Matcher matcher = regEx.matcher(text);
//                System.out.println(matcher.matches());
//                if (!matcher.matches()) {
//                    return;
//                }
//                super.replace(fb, offset, length, text, attrs);
//            }
//        };
    
    /**
     * Creates new form vistaIngresarEmpleados
     */
    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    int sueldo_min;
    int sueldo_base;
    
    public vistaIngresarEmpleados(java.awt.Frame parent, boolean modal, final Object[][] regiones) {
        super(parent, modal);
        initComponents();
        labelIsapre.setVisible(false);
        labelValorPlan.setVisible(false);
        textoIsapre.setVisible(false);
        textoValorPlan.setVisible(false);
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
        String[] listaRegiones = new String[regiones.length];
        for(int i = 0; i < regiones.length; i++){
            listaRegiones[i] = regiones[i][1].toString();
        }
        comboRegion.setModel(new DefaultComboBoxModel<String>(listaRegiones));
        cargarComunas(regiones);
        comboRegion.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                cargarComunas(regiones);
            }
        });
    }
    
    public void cargarComunas(Object[][] regiones){
        controladores.controladorIngresarEmpleados miControlador = new controladorIngresarEmpleados();
        int index = comboRegion.getSelectedIndex();
        int region = Integer.parseInt(regiones[index][0].toString());
        Object[] comunas = miControlador.cargarComunas(region);
        String[] listaComunas = new String[comunas.length];
        for(int i = 0; i < comunas.length; i++){
            listaComunas[i] = comunas[i].toString();
        }
        comboComuna.setModel(new DefaultComboBoxModel<String>(listaComunas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        labelCargo = new javax.swing.JLabel();
        comboCargo = new javax.swing.JComboBox();
        labelSueldo = new javax.swing.JLabel();
        textoSueldo = new javax.swing.JTextField();
        labelAFP = new javax.swing.JLabel();
        comboAFP = new javax.swing.JComboBox();
        labelSalud = new javax.swing.JLabel();
        comboSalud = new javax.swing.JComboBox();
        labelFechaIngreso = new javax.swing.JLabel();
        textoFechaIn = new org.jdesktop.swingx.JXDatePicker();
        labelIsapre = new javax.swing.JLabel();
        textoIsapre = new javax.swing.JTextField();
        labelValorPlan = new javax.swing.JLabel();
        textoValorPlan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoColacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoTransporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoBonoAdicional = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoValorBonoAdicional = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoCaja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textoAF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelDir = new javax.swing.JLabel();
        textoDir = new javax.swing.JTextField();
        labelRegion = new javax.swing.JLabel();
        comboRegion = new javax.swing.JComboBox();
        labelComuna = new javax.swing.JLabel();
        comboComuna = new javax.swing.JComboBox();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        textoCorreo = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        labelRut = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        textoApMaterno = new javax.swing.JTextField();
        textoApPaterno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textoNombres = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        textoFechaNac = new org.jdesktop.swingx.JXDatePicker();
        textoRut = new javax.swing.JTextField();
        labelFechaNac = new javax.swing.JLabel();
        labelApMaterno = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar trabajador");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos sueldos"));

        labelCargo.setText("Cargo");

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jefe(a) de administración y finanzas", "Jefe de operaciones", "Gerente general", "Gerente de administración", "Supervisor", "Administrativo", "Mecánico", "Ayud. mecánico", "Jefe de Mantenciones", "Operador Senior", "Operador" }));

        labelSueldo.setText("Sueldo");

        textoSueldo.setToolTipText("Sueldo contrato indefinido");
        textoSueldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoSueldoFocusLost(evt);
            }
        });

        labelAFP.setText("AFP");

        comboAFP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CUPRUM", "HABITAT", "CAPITAL", "PLANVITAL", "PROVIDA", "MODELO" }));

        labelSalud.setText("Salud");

        comboSalud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fonasa", "Isapre" }));
        comboSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSaludActionPerformed(evt);
            }
        });

        labelFechaIngreso.setText("Fecha de ingreso");

        labelIsapre.setText("Isapre");

        labelValorPlan.setText("Valor plan (UF)");

        textoValorPlan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoValorPlanFocusLost(evt);
            }
        });
        textoValorPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoValorPlanActionPerformed(evt);
            }
        });

        jLabel2.setText("Colación");

        textoColacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoColacionFocusLost(evt);
            }
        });

        jLabel3.setText("Transporte");

        textoTransporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoTransporteFocusLost(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/next.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setText("Bono adicional");

        jLabel6.setText("Valor bono adicional");

        textoValorBonoAdicional.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoValorBonoAdicionalFocusLost(evt);
            }
        });

        jLabel7.setText("Caja de compensación");

        textoCaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoCajaFocusLost(evt);
            }
        });

        jLabel8.setText("Asignación familiar");

        textoAF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textoAFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textoBonoAdicional)
                        .addComponent(labelCargo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelAFP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelFechaIngreso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textoFechaIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboAFP, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textoColacion, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(textoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIsapre)
                            .addComponent(textoIsapre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelValorPlan)
                                .addGap(20, 20, 20))
                            .addComponent(textoValorPlan)))
                    .addComponent(textoTransporte)
                    .addComponent(comboSalud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoSueldo)
                    .addComponent(textoValorBonoAdicional)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(labelSalud)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelSueldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoAF))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargo)
                    .addComponent(labelSueldo)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAFP)
                    .addComponent(labelSalud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaIngreso)
                    .addComponent(labelIsapre)
                    .addComponent(labelValorPlan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoIsapre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoValorPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoColacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBonoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoValorBonoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        labelDir.setText("Dirección");

        labelRegion.setText("Región");

        comboRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelComuna.setText("Comuna");

        comboComuna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDir)
                    .addComponent(labelRegion)
                    .addComponent(labelComuna))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDir)
                    .addComponent(comboRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboComuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDir)
                    .addComponent(textoDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelComuna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        labelRut.setText("Rut");

        labelCorreo.setText("Correo");

        jLabel1.setText("Apellido Paterno");

        labelTelefono.setText("Teléfono");

        labelNombres.setText("Nombres");

        labelFechaNac.setText("Fecha de nacimiento");

        labelApMaterno.setText("Apellido Materno");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCorreo)
                    .addComponent(labelTelefono)
                    .addComponent(labelFechaNac)
                    .addComponent(labelApMaterno)
                    .addComponent(jLabel1)
                    .addComponent(labelNombres)
                    .addComponent(labelRut)
                    .addComponent(textoRut)
                    .addComponent(textoNombres)
                    .addComponent(textoApPaterno)
                    .addComponent(textoApMaterno)
                    .addComponent(textoFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoTelefono)
                    .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelApMaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelFechaNac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        controladores.controladorIngresarEmpleados miControladorIE = new controladores.controladorIngresarEmpleados();
        String respuesta = miControladorIE.camposVacios();
        boolean esVacio = respuesta.length() == 0;
        if(!esVacio){
            JOptionPane.showMessageDialog(this, respuesta, "Debe rellenar los siguientes campos", JOptionPane.INFORMATION_MESSAGE);
        }else{
            boolean rutValido = miControladorIE.verificarRut(getTextoRut());
            if(rutValido){
                if(miControladorIE.irVistaEmpleadosP()) setVisible(false);
            }
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textoSueldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoSueldoFocusLost
        setTextoSueldo(getTextoSueldoBase());
    }//GEN-LAST:event_textoSueldoFocusLost

    private void comboSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSaludActionPerformed
        if(comboSalud.getSelectedIndex() == 0){
            labelIsapre.setVisible(false);
            labelValorPlan.setVisible(false);
            textoIsapre.setVisible(false);
            textoValorPlan.setVisible(false);
        }else{
            labelIsapre.setVisible(true);
            labelValorPlan.setVisible(true);
            textoIsapre.setVisible(true);
            textoValorPlan.setVisible(true);
        }
    }//GEN-LAST:event_comboSaludActionPerformed

    private void textoValorPlanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoValorPlanFocusLost
        //setTextoValorPlan(getTextoValorPlan());
        Pattern regEx = Pattern.compile("^[0-9]+[\\.\\,][0-9]+|[0-9]+$");
        String texto = ((JTextField) evt.getSource()).getText();
        Matcher matcher = regEx.matcher(texto);
        if (!matcher.matches()) {
            textoValorPlan.setText("");
        }
    }//GEN-LAST:event_textoValorPlanFocusLost

    private void textoTransporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoTransporteFocusLost
        setTextoTransporte(getTextoTransporte());
    }//GEN-LAST:event_textoTransporteFocusLost

    private void textoColacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoColacionFocusLost
        setTextoColacion(getTextoColacion());
    }//GEN-LAST:event_textoColacionFocusLost

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        textoSueldo.setText(FORMAT.format(sueldo_base));
    }//GEN-LAST:event_jLabel4MousePressed

    private void textoValorBonoAdicionalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoValorBonoAdicionalFocusLost
        setTextoValorBonoAd(getTextoValorBonoAd());
    }//GEN-LAST:event_textoValorBonoAdicionalFocusLost

    private void textoCajaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoCajaFocusLost
        setTextoCaja(getTextoCaja());
    }//GEN-LAST:event_textoCajaFocusLost

    private void textoAFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoAFFocusLost
        setTextoAF(getTextoAF());
    }//GEN-LAST:event_textoAFFocusLost

    private void textoValorPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoValorPlanActionPerformed
//        System.out.println(evt);
//        Pattern regEx = Pattern.compile("^[0-9]*\\,[0-9]*|[0-9]+$");
//        String texto = ((JTextField) evt.getSource()).getText();
//        Matcher matcher = regEx.matcher(texto);
//        System.out.println(texto);
//        if (!matcher.matches()) {
//            textoValorPlan.setText("");
//        }
    }//GEN-LAST:event_textoValorPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaIngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox comboAFP;
    private javax.swing.JComboBox comboCargo;
    private javax.swing.JComboBox comboComuna;
    private javax.swing.JComboBox comboRegion;
    private javax.swing.JComboBox comboSalud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelAFP;
    private javax.swing.JLabel labelApMaterno;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelComuna;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelIsapre;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelRegion;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel labelSalud;
    private javax.swing.JLabel labelSueldo;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelValorPlan;
    private javax.swing.JTextField textoAF;
    private javax.swing.JTextField textoApMaterno;
    private javax.swing.JTextField textoApPaterno;
    private javax.swing.JTextField textoBonoAdicional;
    private javax.swing.JTextField textoCaja;
    private javax.swing.JTextField textoColacion;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoDir;
    private org.jdesktop.swingx.JXDatePicker textoFechaIn;
    private org.jdesktop.swingx.JXDatePicker textoFechaNac;
    private javax.swing.JTextField textoIsapre;
    private javax.swing.JTextField textoNombres;
    private javax.swing.JTextField textoRut;
    private javax.swing.JTextField textoSueldo;
    private javax.swing.JTextField textoTelefono;
    private javax.swing.JTextField textoTransporte;
    private javax.swing.JTextField textoValorBonoAdicional;
    private javax.swing.JTextField textoValorPlan;
    // End of variables declaration//GEN-END:variables

    public String getComboAFP() {
        return comboAFP.getSelectedItem().toString();
    }

    public String getComboCargo() {
        return comboCargo.getSelectedItem().toString().trim();
    }

    public String getComboComuna() {
        return comboComuna.getSelectedItem().toString();
    }

    public String getComboRegion() {
        return comboRegion.getSelectedItem().toString();
    }

    public String getComboSalud() {
        return comboSalud.getSelectedItem().toString();
    }

    public String getTextoApMaterno() {
        return textoApMaterno.getText().trim();
    }

    public String getTextoApPaterno() {
        return textoApPaterno.getText().trim();
    }

    public String getTextoCorreo() {
        return textoCorreo.getText();
    }

    public String getTextoDir() {
        return textoDir.getText();
    }

    public String  getTextoFechaIn() {
        Date fecha = textoFechaIn.getDate();
        if(fecha == null) return "";
        String dateString = formatDate.format(textoFechaIn.getDate());
        return dateString;
    }

    public String getTextoFechaNac() {
        Date fecha = textoFechaNac.getDate();
        if(fecha == null) return "";
        String dateString = formatDate.format(textoFechaNac.getDate());
        return dateString;
    }

    public String getTextoNombres() {
        String text = textoNombres.getText().trim();
        
        return text.replaceAll("\\s+", " ");
    }

    public String getTextoRut() {
        return textoRut.getText();
    }

    public String getTextoSueldo() {
        String sueldo = textoSueldo.getText();
        sueldo = sueldo.replace("$", "");
        sueldo = sueldo.replace(".", "");
        return sueldo;
    }
    
    public String getTextoColacion() {
        if(textoColacion.getText().compareTo("") == 0){
            return "0";
        }
        String colacion = textoColacion.getText();
        colacion = colacion.replace("$", "");
        colacion = colacion.replace(".", "");
        return colacion;
    }
    public String getTextoTransporte() {
        if(textoTransporte.getText().compareTo("") == 0){
            return "0";
        }
        String transporte = textoTransporte.getText();
        transporte = transporte.replace("$", "");
        transporte = transporte.replace(".", "");
        return transporte;
    }

    public String getTextoTelefono() {
        return textoTelefono.getText();
    }

    public void setSueldoMin(int sueldo){
        sueldo_min = sueldo;
    }

    public void setSueldoBase(int sueldo){
        sueldo_base = sueldo;
    }
    
    public int getSueldoMin(){
        return sueldo_min;
    }
    
    public int getSueldoBase(){
        return sueldo_base;
    }
    
    public String getIsapre(){
        return textoIsapre.getText();
    }
    
    public String getValorIsapre(){
        String valor = textoValorPlan.getText();
        if(valor.compareTo("") == 0){
            return "0";
        }
        valor = valor.replace("$", "");
        valor = valor.replace(",", ".");
        return valor;
    }
    
    public void setTextoSueldo(String base){
        try{
            Object value = Integer.parseInt(base);
            if (value instanceof Number) {
                textoSueldo.setHorizontalAlignment(JLabel.RIGHT);
                if(((Number) value).intValue() < sueldo_min) value = sueldo_min;
                textoSueldo.setText(FORMAT.format(value));
            } else {
                textoSueldo.setHorizontalAlignment(JLabel.RIGHT);
                textoSueldo.setText("");
                textoSueldo.setText(FORMAT.format(sueldo_min));
            }
        }catch(NumberFormatException e){
            textoSueldo.setHorizontalAlignment(JLabel.RIGHT);
            textoSueldo.setText("");
            textoSueldo.setText(FORMAT.format(sueldo_min));
        }
    }
    
    public void setTextoValorPlan(String val){
        try{
            Object value = Integer.parseInt(val);
            if (value instanceof Number) {
                textoValorPlan.setHorizontalAlignment(JLabel.RIGHT);
                textoValorPlan.setText(FORMAT.format(value));
            } else {
                textoValorPlan.setHorizontalAlignment(JLabel.RIGHT);
                textoValorPlan.setText("");
            }
        }catch(NumberFormatException e){
            textoValorPlan.setHorizontalAlignment(JLabel.RIGHT);
            textoValorPlan.setText("");
        }
    }
    
    public void setTextoTransporte(String trans){
        try{
            Object value = Integer.parseInt(trans);
            if (value instanceof Number) {
                textoTransporte.setHorizontalAlignment(JLabel.RIGHT);
                textoTransporte.setText(FORMAT.format(value));
            } else {
                textoTransporte.setHorizontalAlignment(JLabel.RIGHT);
                textoTransporte.setText("");
            }
        }catch(NumberFormatException e){
            textoTransporte.setHorizontalAlignment(JLabel.RIGHT);
            textoTransporte.setText("");
        }
    }
    
    public void setTextoColacion(String col){
        try{
            Object value = Integer.parseInt(col);
            if (value instanceof Number) {
                textoColacion.setHorizontalAlignment(JLabel.RIGHT);
                textoColacion.setText(FORMAT.format(value));
            } else {
                textoColacion.setHorizontalAlignment(JLabel.RIGHT);
                textoColacion.setText("");
            }
        }catch(NumberFormatException e){
            textoColacion.setHorizontalAlignment(JLabel.RIGHT);
            textoColacion.setText("");
        }
    }
    
    public void setTextoValorBonoAd(String val){
        try{
            Object value = Integer.parseInt(val);
            if (value instanceof Number) {
                textoValorBonoAdicional.setHorizontalAlignment(JLabel.RIGHT);
                textoValorBonoAdicional.setText(FORMAT.format(value));
            } else {
                textoValorBonoAdicional.setHorizontalAlignment(JLabel.RIGHT);
                textoValorBonoAdicional.setText("");
            }
        }catch(NumberFormatException e){
            textoValorBonoAdicional.setHorizontalAlignment(JLabel.RIGHT);
            textoValorBonoAdicional.setText("");
        }
    }
    
    public void setTextoCaja(String caja){
        try{
            Object value = Integer.parseInt(caja);
            if (value instanceof Number) {
                textoCaja.setHorizontalAlignment(JLabel.RIGHT);
                textoCaja.setText(FORMAT.format(value));
            } else {
                textoCaja.setHorizontalAlignment(JLabel.RIGHT);
                textoCaja.setText("");
            }
        }catch(NumberFormatException e){
            textoCaja.setHorizontalAlignment(JLabel.RIGHT);
            textoCaja.setText("");
        }
    }
    
    public void setTextoAF(String af){
        try{
            Object value = Integer.parseInt(af);
            if (value instanceof Number) {
                textoAF.setHorizontalAlignment(JLabel.RIGHT);
                textoAF.setText(FORMAT.format(value));
            } else {
                textoAF.setHorizontalAlignment(JLabel.RIGHT);
                textoAF.setText("");
            }
        }catch(NumberFormatException e){
            textoAF.setHorizontalAlignment(JLabel.RIGHT);
            textoAF.setText("");
        }
    }
    
    public String getTextoSueldoBase() {
        String base = textoSueldo.getText().replace("$", "");
        base = base.replace(".", "");
        return base;
    }
    
    public String getTextoValorPlan() {
        String val = textoValorPlan.getText().replace("$", "");
        val = val.replace(",", ".");
        return val;
    }
    
    public String getTextoBonoAd(){
        if(textoBonoAdicional.getText().compareTo("") == 0){
            return "";
        }else{
            return textoBonoAdicional.getText();
        }
    }
    
    public String getTextoValorBonoAd(){
        String val = textoValorBonoAdicional.getText().replace("$", "");
        val = val.replace(".", "");
        if(val.compareTo("") == 0) return "0";
        return val;
    }
    
    public String getTextoCaja(){
        String val = textoCaja.getText().replace("$", "");
        val = val.replace(".", "");
        if(val.compareTo("") == 0) return "0";
        return val;
    }
    
    public String getTextoAF(){
        String val = textoAF.getText().replace("$", "");
        val = val.replace(".", "");
        if(val.compareTo("") == 0) return "0";
        return val;
    }
    
}
