/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.EventQueue;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import modelos.modeloClientes;

/**
 *
 * @author diego
 */
public class vistaModificarJornadas extends javax.swing.JDialog {

    /**
     * Creates new form vistaModificarJornadas
     */
    String id;
    
    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    DateFormat formatClock = new SimpleDateFormat("HH:mm");
    DateFormat formateDateTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    DateFormat formatDia = new SimpleDateFormat("EEE");
//    TextAutoCompleter listaGruas;
//    TextAutoCompleter listaEmpleados;
    Vector<String> vectorClientes = new Stack<String>();
    Vector<String> vectorGruas = new Stack<String>();
    Vector<String> vectorEmpleados = new Stack<String>();
    JTextField textoClientes = new JTextField();
    JTextField textoOperadores = new JTextField();
    JTextField textoGruas = new JTextField();
    private boolean hide_flag = false;
    
    public vistaModificarJornadas(java.awt.Frame parent, boolean modal, Object[] clientes,
            Object[] gruas, Object[] empleados) {
        super(parent, modal);
        initComponents();
//        TextAutoCompleter listaClientes = new TextAutoCompleter(textoCliente);
//        listaGruas = new TextAutoCompleter(textoGrua);
//        listaEmpleados = new TextAutoCompleter(textoEmpleado);
//        for(int i = 0; i < clientes.length; i++){
//            listaClientes.addItem(clientes[i].toString());
//        }
//        for(int i = 0; i < gruas.length; i++){
//            listaGruas.addItem(gruas[i].toString());
//        }
//        for(int i = 0; i < empleados.length; i++){
//            listaEmpleados.addItem(empleados[i].toString());
//        }
        textoClientes = (JTextField)comboClientes.getEditor().getEditorComponent();
        textoGruas = (JTextField)comboGruas.getEditor().getEditorComponent();
        textoOperadores = (JTextField)comboOperadores.getEditor().getEditorComponent();
        modelos.modeloClientes cliente = new modeloClientes();
        textoGruas.addFocusListener(new FocusListener(){
                @Override
                public void focusGained(FocusEvent e){
                    modelos.modeloGruas grua = new modelos.modeloGruas();
                    Object[] gruas = grua.obtenerDescGruasDisp(getTextoFechaSalida() + " " + getTextoHoraSalida(),
                getTextoFechaRegreso() + " " + getTextoHoraRegreso());
                    autosuggestGruas(gruas);
                }

            @Override
            public void focusLost(FocusEvent fe) {
            }
            });
        textoOperadores.addFocusListener(new FocusListener(){
            @Override
            public void focusGained(FocusEvent e){
        modelos.modeloEmpleados empleado = new modelos.modeloEmpleados();
        Object[] empleados = empleado.obtenerNomEmpDisp(getTextoFechaSalida() + " " + getTextoHoraSalida(),
                getTextoFechaRegreso() + " " + getTextoHoraRegreso());
        autosuggestOperadores(empleados);
            }
            @Override
            public void focusLost(FocusEvent fe) {
            }
        });
        autosuggestClientes(clientes);
        autosuggestGruas(gruas);
        autosuggestOperadores(empleados);
        String obs = cliente.obtenerObsPorRazon(getComboCliente());
        setTextoObsCliente(obs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFechaSalida = new javax.swing.JLabel();
        textoFechaSalida = new org.jdesktop.swingx.JXDatePicker();
        labelHoraSalida = new javax.swing.JLabel();
        textoHoraSalida = new javax.swing.JSpinner(new SpinnerDateModel());
        labelGrua = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelOperador = new javax.swing.JLabel();
        labelFechaRegreso = new javax.swing.JLabel();
        textoFechaRegreso = new org.jdesktop.swingx.JXDatePicker();
        labelHoraRegreso = new javax.swing.JLabel();
        textoHoraRegreso = new javax.swing.JSpinner(new SpinnerDateModel());
        labelObs = new javax.swing.JLabel();
        scrollpan = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObsCliente = new javax.swing.JTextArea();
        labelObsCliente = new javax.swing.JLabel();
        comboOperadores = new javax.swing.JComboBox();
        comboGruas = new javax.swing.JComboBox();
        comboClientes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar jornada de trabajo");

        labelFechaSalida.setText("Fecha de salida");

        labelHoraSalida.setText("Hora de salida");

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(textoHoraSalida, "HH:mm");
        textoHoraSalida.setEditor(timeEditor);
        textoHoraSalida.setValue(new Date());

        labelGrua.setText("Grúa");

        labelCliente.setText("Cliente");

        labelOperador.setText("Operador");

        labelFechaRegreso.setText("Fecha de regreso");

        labelHoraRegreso.setText("Hora de regreso");

        JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(textoHoraRegreso, "HH:mm");
        textoHoraRegreso.setEditor(timeEditor2);
        textoHoraRegreso.setValue(new Date());

        labelObs.setText("Observaciones");

        textoObs.setColumns(20);
        textoObs.setRows(5);
        scrollpan.setViewportView(textoObs);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        textoObsCliente.setColumns(20);
        textoObsCliente.setRows(5);
        jScrollPane1.setViewportView(textoObsCliente);

        labelObsCliente.setText("Observaciones cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelObsCliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(comboGruas, 0, 274, Short.MAX_VALUE)
                    .addComponent(comboClientes, 0, 274, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoHoraRegreso)
                    .addComponent(textoFechaRegreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollpan, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addComponent(labelOperador)
                                    .addComponent(labelObs)
                                    .addComponent(labelFechaRegreso)
                                    .addComponent(labelHoraRegreso))
                                .addGap(8, 8, 8))
                            .addComponent(comboOperadores, javax.swing.GroupLayout.Alignment.LEADING, 0, 295, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelHoraSalida)
                        .addComponent(labelGrua)
                        .addComponent(labelCliente)
                        .addComponent(labelFechaSalida)
                        .addComponent(textoFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addComponent(textoHoraSalida))
                    .addContainerGap(342, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFechaRegreso)
                .addGap(5, 5, 5)
                .addComponent(textoFechaRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHoraRegreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoHoraRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGruas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelObs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelObsCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelFechaSalida)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(textoFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(labelHoraSalida)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(textoHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(labelGrua)
                    .addGap(37, 37, 37)
                    .addComponent(labelCliente)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        JFrame tabs = (JFrame)this.getParent();
        System.out.println(tabs.getTitle());
        controladores.controladorModificarJornadas miControladorMJ = new controladores.controladorModificarJornadas();
        String respuesta = miControladorMJ.camposVacios();
        boolean esVacio = respuesta.length() == 0;
        if (!esVacio) {
            JOptionPane.showMessageDialog(this, respuesta, "Debe rellenar los siguientes campos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                if (miControladorMJ.irVistaJornadasP()) {
                    setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Se generó un error al ingresar la jornada\n"
                        + "Por favor compruebe que el cliente, grúa y empleados sean correctos", "Error" , JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (ParseException ex) {
                Logger.getLogger(vistaModificarJornadas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaModificarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaModificarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaModificarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaModificarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox comboClientes;
    private javax.swing.JComboBox comboGruas;
    private javax.swing.JComboBox comboOperadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFechaRegreso;
    private javax.swing.JLabel labelFechaSalida;
    private javax.swing.JLabel labelGrua;
    private javax.swing.JLabel labelHoraRegreso;
    private javax.swing.JLabel labelHoraSalida;
    private javax.swing.JLabel labelObs;
    private javax.swing.JLabel labelObsCliente;
    private javax.swing.JLabel labelOperador;
    private javax.swing.JScrollPane scrollpan;
    private org.jdesktop.swingx.JXDatePicker textoFechaRegreso;
    private org.jdesktop.swingx.JXDatePicker textoFechaSalida;
    private javax.swing.JSpinner textoHoraRegreso;
    private javax.swing.JSpinner textoHoraSalida;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextArea textoObsCliente;
    // End of variables declaration//GEN-END:variables

    public void setTextoCliente(String comboCliente) {
        this.comboClientes.setSelectedItem(comboCliente);
    }

    public void setTextoGrua(String comboGrua) {
        this.comboGruas.setSelectedItem(comboGrua);
    }

    public void setTextoOperador(String comboOperador) {
        this.comboOperadores.setSelectedItem(comboOperador.trim());
    }

    public void setTextoFechaRegreso(String textoFechaRegreso) throws ParseException {
        this.textoFechaRegreso.setDate(formatDate.parse(textoFechaRegreso));
    }

    public void setTextoFechaSalida(String textoFechaSalida) throws ParseException {
        this.textoFechaSalida.setDate(formatDate.parse(textoFechaSalida));
    }

    public void setTextoHoraRegreso(String textoHoraRegreso) throws ParseException {
        this.textoHoraRegreso.setValue(formatClock.parse(textoHoraRegreso));
    }

    public void setTextoHoraSalida(String textoHoraSalida) throws ParseException {
        this.textoHoraSalida.setValue(formatClock.parse(textoHoraSalida));
    }

    public void setTextoObs(String textoObs) {
        this.textoObs.setText(textoObs);
    }
    
    public void setId(String id){
        this.id = id;
    }
    
    public String getTextoFechaRegreso() {
        Date fecha = textoFechaRegreso.getDate();
        if(fecha == null) return "";
        String dateString = formatDate.format(textoFechaRegreso.getDate());
        return dateString;
    }
    
    public String getDiaSalida(){
        Date fecha = textoFechaSalida.getDate();
        if(fecha == null) return "";
        String dia = formatDia.format(textoFechaSalida.getDate());
        return dia;
    }
    
    public String getDiaRegreso(){
        Date fecha = textoFechaRegreso.getDate();
        if(fecha == null) return "";
        String dia = formatDia.format(textoFechaRegreso.getDate());
        return dia;
    }

    public String getTextoFechaSalida() {
        Date fecha = textoFechaSalida.getDate();
        if(fecha == null) return "";
        String dateString = formatDate.format(textoFechaSalida.getDate());
        return dateString;    
    }

    public String getTextoHoraRegreso() {
        String hora = formatClock.format(textoHoraRegreso.getValue());
        if(hora == null) return "";
        return hora;
    }

    public String getTextoHoraSalida() {
        String hora = formatClock.format(textoHoraSalida.getValue());
        if(hora == null) return "";
        return hora;
    }

    public String getTextoObs() {
        return textoObs.getText();
    }

    public String getComboCliente() {
        return comboClientes.getSelectedItem().toString();
    }

    public String getComboGrua() {
        return comboGruas.getSelectedItem().toString();
    }

    public String getComboOperador() {
        return comboOperadores.getSelectedItem().toString();
    }
    
    public String getId(){
        return id;
    }
    
    public void setTextoObsCliente(String textoObsCliente) {
        this.textoObsCliente.setText(textoObsCliente);
    }
    
    private void setModel(DefaultComboBoxModel mdl, String str, JComboBox combo, JTextField texto){
        combo.setModel(mdl);
        texto.setText(str);
    }
    
    private DefaultComboBoxModel getSuggestedModel(List<String> list, String tx){
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String s : list){
            if(s.toLowerCase().contains(tx.toLowerCase())){
                m.addElement(s);
            }
        }
        return m;
    }
    
    public void autosuggestClientes(Object[] data){
            comboClientes.removeAllItems();
            if(comboClientes.getItemCount() == 0){
                for (Object data1 : data) {
                    comboClientes.addItem(data1);
                    vectorClientes.addElement((String) data1);
                    comboClientes.addItemListener(new ItemListener() {

                        @Override
                        public void itemStateChanged(ItemEvent ie) {
                            if(ie.getStateChange() == ItemEvent.SELECTED){
                                comboClientes.getSelectedIndex();
                            }
                        }
                    });
                }
            }else{
                comboClientes.addItem("Error");
            }

        comboClientes.setEditable(true);
        textoClientes.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        String text = textoClientes.getText();
                        if(text.length() == 0){
                            comboClientes.hidePopup();
                            setModel(new DefaultComboBoxModel(vectorClientes), "", comboClientes, textoClientes);
                        }else{
                            DefaultComboBoxModel m = getSuggestedModel(vectorClientes, text);
                            if(m.getSize() == 0){
                                comboClientes.hidePopup();
                            }else{
                                setModel(m, text, comboClientes, textoClientes);
                                comboClientes.showPopup();
                            }
                        }
                    }
                });
            }
            
            @Override
            public void keyPressed(KeyEvent e){
                String text = textoClientes.getText();
                int code = e.getKeyCode();
                if(code == KeyEvent.VK_ENTER){
                    for (int i = 0; i < vectorClientes.size(); i++) {
                        String str = (String)vectorClientes.elementAt(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoClientes.setText(str);
                            modelos.modeloClientes cliente = new modeloClientes();
                            String obs = cliente.obtenerObsPorRazon(comboClientes.getSelectedItem().toString());
                            setTextoObsCliente(obs);
                            return;
                        }
                    }
                }else if(code == KeyEvent.VK_ESCAPE){
                    hide_flag = true;
                }else if(code == KeyEvent.VK_RIGHT){
                    for (int i = 0; i < vectorClientes.size(); i++) {
                        String str = (String)vectorClientes.elementAt(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoClientes.setText(str);
                            modelos.modeloClientes cliente = new modeloClientes();
                            String obs = cliente.obtenerObsPorRazon(comboClientes.getSelectedItem().toString());
                            setTextoObsCliente(obs);
                            return;
                        }
                    }
                }
            }
            
//            public void mousePressed(MouseEvent e){
//                String text = textoClientes.getText();
//                int code = e.getButton();
//                if(code == MouseEvent.BUTTON1){
//                    modelos.modeloClientes cliente = new modeloClientes();
//                            String obs = cliente.obtenerObsPorRazon(comboClientes.getSelectedItem().toString());
//                            setTextoObsCliente(obs);
//                }
//            }
        });
    }
    
    public void autosuggestGruas(Object[] data){
            comboGruas.removeAllItems();
            vectorGruas.removeAllElements();
            if(comboGruas.getItemCount() == 0){
                for (int j = 0; j < data.length; j++) {
                    comboGruas.addItem(data[j]);
                    vectorGruas.addElement((String)data[j]);
                    comboGruas.addItemListener(new ItemListener() {

                        @Override
                        public void itemStateChanged(ItemEvent ie) {
                            if(ie.getStateChange() == ItemEvent.SELECTED){
                                comboGruas.getSelectedIndex();
                            }
                        }
                    });

                }
            }else{
                comboGruas.addItem("Error");
            }

        comboGruas.setEditable(true);
        textoGruas.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        String text = textoGruas.getText();
                        if(text.length() == 0){
                            comboGruas.hidePopup();
                            setModel(new DefaultComboBoxModel(vectorGruas), "", comboGruas, textoGruas);
                        }else{
                            DefaultComboBoxModel m = getSuggestedModel(vectorGruas, text);
                            if(m.getSize() == 0){
                                comboGruas.hidePopup();
                            }else{
                                setModel(m, text, comboGruas, textoGruas);
                                comboGruas.showPopup();
                            }
                        }
                    }
                });
            }
            
            @Override
            public void keyPressed(KeyEvent e){
                String text = textoGruas.getText();
                int code = e.getKeyCode();
                if(code == KeyEvent.VK_ENTER){
                    for (int i = 0; i < vectorGruas.size(); i++) {
                        String str = (String)vectorGruas.elementAt(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoGruas.setText(str);
                            return;
                        }
                    }
                }else if(code == KeyEvent.VK_ESCAPE){
                    hide_flag = true;
                }else if(code == KeyEvent.VK_RIGHT){
                    for (int i = 0; i < vectorGruas.size(); i++) {
                        String str = (String)vectorGruas.elementAt(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoGruas.setText(str);
                            return;
                        }
                    }
                }
            }
        });
    }

    public void autosuggestOperadores(Object[] data){
            comboOperadores.removeAllItems();
            vectorEmpleados.removeAllElements();
            if(comboOperadores.getItemCount() == 0){
                for (Object data1 : data) {
                    comboOperadores.addItem(data1);
                    vectorEmpleados.addElement((String) data1);
                    comboOperadores.addItemListener(new ItemListener() {

                        @Override
                        public void itemStateChanged(ItemEvent ie) {
                            if(ie.getStateChange() == ItemEvent.SELECTED){
                                comboOperadores.getSelectedIndex();
                            }
                        }
                    });
                }
            }else{
                comboOperadores.addItem("Error");
            }

        comboOperadores.setEditable(true);
        textoOperadores.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        String text = textoOperadores.getText();
                        if(text.length() == 0){
                            comboOperadores.hidePopup();
                            setModel(new DefaultComboBoxModel(vectorEmpleados), "", comboOperadores, textoOperadores);
                        }else{
                            DefaultComboBoxModel m = getSuggestedModel(vectorEmpleados, text);
                            if(m.getSize() == 0){
                                comboOperadores.hidePopup();
                            }else{
                                setModel(m, text, comboOperadores, textoOperadores);
                                comboOperadores.showPopup();
                            }
                        }
                    }
                });
            }
            
            @Override
            public void keyPressed(KeyEvent e){
                String text = textoOperadores.getText();
                int code = e.getKeyCode();
                if(code == KeyEvent.VK_ENTER){
                    for (int i = 0; i < vectorEmpleados.size(); i++) {
                        String str = (String)vectorEmpleados.elementAt(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoOperadores.setText(str);
                            return;
                        }
                    }
                }else if(code == KeyEvent.VK_ESCAPE){
                    hide_flag = true;
                }else if(code == KeyEvent.VK_RIGHT){
                    for (int i = 0; i < vectorEmpleados.size(); i++) {
                        String str = (String)vectorEmpleados.elementAt(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoOperadores.setText(str);
                            return;
                        }
                    }
                }
            }
        });
    }
}
