/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class vistaControlGruas extends javax.swing.JFrame {

    /**
     * Creates new form vistaControlGruas
     */
    Object[][] datos;
    public vistaControlGruas(String tipo, Object[][] data) {
        pack();
        setSize(800, 600);
        setLocationRelativeTo(null);
        initComponents();
        String[] columNames = {"Patente", "Descripción", "Marca", "Modelo", "Tonelaje"};
        DefaultTableModel datos = new DefaultTableModel(data, columNames){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablaGruas.setModel(datos);
        tablaGruas.setRowSelectionInterval(0, 0);
        tablaGruas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaGruas.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent evt){
                JTable table = (JTable)evt.getSource();
                Point p = evt.getPoint();
                int row = table.rowAtPoint(p);
                if(evt.getClickCount() == 2){
                    controladores.controladorGruas miControlador = new controladores.controladorGruas();
                    try {
                        miControlador.irVistaDetalleGrua(tablaGruas.getValueAt(row, 0).toString());
                    } catch (ParseException ex) {
                        Logger.getLogger(vistaControlGruas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGruas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGruas = new javax.swing.JTable();
        botonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuUsuarios = new javax.swing.JMenu();
        MenuCambioClave = new javax.swing.JMenuItem();
        MenuControlUsuarios = new javax.swing.JMenuItem();
        MenuAgenda = new javax.swing.JMenu();
        MenuJornadaDiaria = new javax.swing.JMenuItem();
        MenuGestionAgendas = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        MenuControlClientes = new javax.swing.JMenuItem();
        MenuEmpleados = new javax.swing.JMenu();
        MenuControlEmpleados = new javax.swing.JMenuItem();
        MenuLiquidaciones = new javax.swing.JMenuItem();
        MenuFiniquitos = new javax.swing.JMenuItem();
        MenuGruas = new javax.swing.JMenu();
        MenuControlGruas = new javax.swing.JMenuItem();
        MenuCaja = new javax.swing.JMenu();
        MenuCobranza = new javax.swing.JMenu();
        MenuFacturacion = new javax.swing.JMenu();
        MenuMantenciones = new javax.swing.JMenu();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Gruas");
        setPreferredSize(new java.awt.Dimension(800, 600));

        PanelGruas.setToolTipText("");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grúas"));

        tablaGruas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patente", "Descripción", "Marca", "Modelo", "Tonelaje"
            }
        ));
        jScrollPane1.setViewportView(tablaGruas);

        botonAgregar.setText("Agregar grúa");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar grúa");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar grúa");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGruasLayout = new javax.swing.GroupLayout(PanelGruas);
        PanelGruas.setLayout(PanelGruasLayout);
        PanelGruasLayout.setHorizontalGroup(
            PanelGruasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGruasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGruasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGruasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelGruasLayout.setVerticalGroup(
            PanelGruasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGruasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(PanelGruasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonEliminar)
                    .addComponent(botonModificar))
                .addGap(30, 30, 30))
        );

        MenuArchivo.setText("Archivo");

        MenuUsuarios.setText("Usuarios");

        MenuCambioClave.setText("Cambio de clave");
        MenuUsuarios.add(MenuCambioClave);

        MenuControlUsuarios.setText("Control de usuarios");
        MenuUsuarios.add(MenuControlUsuarios);

        MenuArchivo.add(MenuUsuarios);

        MenuAgenda.setText("Agenda");

        MenuJornadaDiaria.setText("Jornada diaria");
        MenuAgenda.add(MenuJornadaDiaria);

        MenuGestionAgendas.setText("Gestión de agendas");
        MenuAgenda.add(MenuGestionAgendas);

        MenuArchivo.add(MenuAgenda);

        MenuClientes.setText("Clientes");

        MenuControlClientes.setText("Control de clientes");
        MenuControlClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlClientesActionPerformed(evt);
            }
        });
        MenuClientes.add(MenuControlClientes);

        MenuArchivo.add(MenuClientes);

        MenuEmpleados.setText("Empleados");

        MenuControlEmpleados.setText("Control de empleados");
        MenuControlEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlEmpleadosActionPerformed(evt);
            }
        });
        MenuEmpleados.add(MenuControlEmpleados);

        MenuLiquidaciones.setText("Liquidaciones");
        MenuEmpleados.add(MenuLiquidaciones);

        MenuFiniquitos.setText("Finiquitos");
        MenuEmpleados.add(MenuFiniquitos);

        MenuArchivo.add(MenuEmpleados);

        MenuGruas.setText("Grúas");

        MenuControlGruas.setText("Control de grúas");
        MenuGruas.add(MenuControlGruas);

        MenuArchivo.add(MenuGruas);

        MenuPrincipal.add(MenuArchivo);

        MenuCaja.setText("Caja");
        MenuPrincipal.add(MenuCaja);

        MenuCobranza.setText("Cobranza");
        MenuPrincipal.add(MenuCobranza);

        MenuFacturacion.setText("Facturación");
        MenuPrincipal.add(MenuFacturacion);

        MenuMantenciones.setText("Mantenciones");
        MenuPrincipal.add(MenuMantenciones);

        MenuAyuda.setText("Ayuda");
        MenuPrincipal.add(MenuAyuda);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGruas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGruas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelGruas.getAccessibleContext().setAccessibleName("Gruas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuControlClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlClientesActionPerformed
        this.setVisible(false);
        controladores.controladorPrincipal miControlador = new controladores.controladorPrincipal();
        miControlador.crearControladorClientes();
    }//GEN-LAST:event_MenuControlClientesActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        controladores.controladorGruas miControlador = new controladores.controladorGruas();
        miControlador.irVistaIngresarGruas();   
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        controladores.controladorGruas miControlador = new controladores.controladorGruas();
        String patente;
        int row = getFilaSeleccionada();
        patente = getPatenteFila(row);
        int dialogResult = JOptionPane.showOptionDialog(rootPane, "Esta seguro que desea eliminar la grúa: \n "
                + patente, "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, 0);
        if(dialogResult == JOptionPane.YES_OPTION)  miControlador.eliminarGruas(patente);
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void MenuControlEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlEmpleadosActionPerformed
        this.setVisible(false);
        controladores.controladorPrincipal miControlador = new controladores.controladorPrincipal();
        miControlador.crearControladorEmpleados();
    }//GEN-LAST:event_MenuControlEmpleadosActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        controladores.controladorGruas miControlador = new controladores.controladorGruas();
        boolean selected = tablaGruas.getSelectedRowCount() > 0;
        if(selected){
            int row = getFilaSeleccionada();
            String patente = getPatenteFila(row);
            String descripcion = getDescripcionFila(row);
            try {
                miControlador.irVistaModificarGruas(patente, descripcion);
            } catch (ParseException ex) {
                Logger.getLogger(vistaControlGruas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una grúa para ser modificada");
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaControlGruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaControlGruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaControlGruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaControlGruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new vistaControlGruas(data).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAgenda;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuCaja;
    private javax.swing.JMenuItem MenuCambioClave;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuCobranza;
    private javax.swing.JMenuItem MenuControlClientes;
    private javax.swing.JMenuItem MenuControlEmpleados;
    private javax.swing.JMenuItem MenuControlGruas;
    private javax.swing.JMenuItem MenuControlUsuarios;
    private javax.swing.JMenu MenuEmpleados;
    private javax.swing.JMenu MenuFacturacion;
    private javax.swing.JMenuItem MenuFiniquitos;
    private javax.swing.JMenuItem MenuGestionAgendas;
    private javax.swing.JMenu MenuGruas;
    private javax.swing.JMenuItem MenuJornadaDiaria;
    private javax.swing.JMenuItem MenuLiquidaciones;
    private javax.swing.JMenu MenuMantenciones;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuUsuarios;
    private javax.swing.JPanel PanelGruas;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGruas;
    // End of variables declaration//GEN-END:variables
    public int getFilaSeleccionada() {
        return tablaGruas.getSelectedRow();
    }
    
    public String getPatenteFila(int row){
        return tablaGruas.getValueAt(row, 0).toString();
    }
    
    public String getDescripcionFila(int row){
        return tablaGruas.getValueAt(row, 1).toString();
    }
}
