/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.controladorPrincipal;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class vistaControlClientes extends javax.swing.JFrame {

    /**
     * Creates new form vistaControlClientes
     */
    Object[][] data;
    
    public vistaControlClientes(String tipo, Object[][] data) {
        initComponents();
        setLocationRelativeTo(null);
        String[] columNames = {"Rut", "Nombre", "Teléfono", "Dirección", "Razón social"};
        DefaultTableModel datos = new DefaultTableModel(data, columNames){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablaClientes.setModel(datos);
        tablaClientes.setRowSelectionInterval(0, 0);
        tablaClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaClientes.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent evt){
                JTable table = (JTable)evt.getSource();
                Point p = evt.getPoint();
                int row = table.rowAtPoint(p);
                if(evt.getClickCount() == 2){
                    controladores.controladorClientes miControlador = new controladores.controladorClientes();
                    miControlador.irVistaDetalleCliente(tablaClientes.getValueAt(row, 0).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        botonAgregarCliente = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuUsuarios = new javax.swing.JMenu();
        MenuCambioClave = new javax.swing.JMenuItem();
        MenuControlUsuarios = new javax.swing.JMenuItem();
        MenuAgenda = new javax.swing.JMenu();
        MenuJornadaDiaria = new javax.swing.JMenuItem();
        MenuGestionAgendas = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        MenuControlClientes = new javax.swing.JMenuItem();
        MenuEmpleados = new javax.swing.JMenu();
        MenuControlEmpleados = new javax.swing.JMenuItem();
        MenuLiquidaciones = new javax.swing.JMenuItem();
        MenuFiniquitos = new javax.swing.JMenuItem();
        MenuGruas = new javax.swing.JMenu();
        MenuControlGruas = new javax.swing.JMenuItem();
        MenuCaja = new javax.swing.JMenu();
        MenuCobranza = new javax.swing.JMenu();
        MenuFacturacion = new javax.swing.JMenu();
        MenuMantenciones = new javax.swing.JMenu();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Clientes");
        setPreferredSize(new java.awt.Dimension(800, 600));

        PanelClientes.setToolTipText("");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "Teléfono", "Dirección", "Razón social"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setHeaderValue("Rut");
            tablaClientes.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            tablaClientes.getColumnModel().getColumn(2).setHeaderValue("Teléfono");
            tablaClientes.getColumnModel().getColumn(3).setHeaderValue("Dirección");
            tablaClientes.getColumnModel().getColumn(4).setHeaderValue("Razón social");
        }

        botonAgregarCliente.setText("Agregar Cliente");
        botonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarClienteActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar Cliente");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar Cliente");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAgregarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificar)))
                .addGap(14, 14, 14))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonAgregarCliente)
                    .addComponent(botonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        MenuArchivo.setText("Archivo");

        MenuUsuarios.setText("Usuarios");

        MenuCambioClave.setText("Cambio de clave");
        MenuUsuarios.add(MenuCambioClave);

        MenuControlUsuarios.setText("Control de usuarios");
        MenuUsuarios.add(MenuControlUsuarios);

        MenuArchivo.add(MenuUsuarios);

        MenuAgenda.setText("Agenda");

        MenuJornadaDiaria.setText("Jornada diaria");
        MenuAgenda.add(MenuJornadaDiaria);

        MenuGestionAgendas.setText("Gestión de agendas");
        MenuAgenda.add(MenuGestionAgendas);

        MenuArchivo.add(MenuAgenda);

        MenuClientes.setText("Clientes");

        MenuControlClientes.setText("Control de clientes");
        MenuClientes.add(MenuControlClientes);

        MenuArchivo.add(MenuClientes);

        MenuEmpleados.setText("Empleados");

        MenuControlEmpleados.setText("Control de empleados");
        MenuControlEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlEmpleadosActionPerformed(evt);
            }
        });
        MenuEmpleados.add(MenuControlEmpleados);

        MenuLiquidaciones.setText("Liquidaciones");
        MenuEmpleados.add(MenuLiquidaciones);

        MenuFiniquitos.setText("Finiquitos");
        MenuEmpleados.add(MenuFiniquitos);

        MenuArchivo.add(MenuEmpleados);

        MenuGruas.setText("Grúas");

        MenuControlGruas.setText("Control de grúas");
        MenuControlGruas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlGruasActionPerformed(evt);
            }
        });
        MenuGruas.add(MenuControlGruas);

        MenuArchivo.add(MenuGruas);

        MenuPrincipal.add(MenuArchivo);

        MenuCaja.setText("Caja");
        MenuPrincipal.add(MenuCaja);

        MenuCobranza.setText("Cobranza");
        MenuPrincipal.add(MenuCobranza);

        MenuFacturacion.setText("Facturación");
        MenuPrincipal.add(MenuFacturacion);

        MenuMantenciones.setText("Mantenciones");
        MenuPrincipal.add(MenuMantenciones);

        MenuAyuda.setText("Ayuda");
        MenuPrincipal.add(MenuAyuda);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelClientes.getAccessibleContext().setAccessibleName("Clientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuControlGruasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlGruasActionPerformed
        this.setVisible(false);
        controladores.controladorPrincipal miControlador = new controladores.controladorPrincipal();
        miControlador.crearControladorGruas();
    }//GEN-LAST:event_MenuControlGruasActionPerformed

    private void botonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarClienteActionPerformed
        controladores.controladorClientes miControlador = new controladores.controladorClientes();
        miControlador.irVistaIngresarClientes();
    }//GEN-LAST:event_botonAgregarClienteActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        controladores.controladorClientes miControlador = new controladores.controladorClientes();
        String rut, nombres, apP;
        int row = getFilaSeleccionada();
        rut = getRutFila(row);
        nombres = getNombresFila(row);
        apP = getApPaternoFila(row);
        int dialogResult = JOptionPane.showOptionDialog(rootPane, "Esta seguro que desea eliminar el cliente: \n "
                + rut + " " + nombres + " " + apP, "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, 0);
        if(dialogResult == JOptionPane.YES_OPTION)  miControlador.eliminarClientes(rut);
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        controladores.controladorClientes miControlador = new controladores.controladorClientes();
        boolean selected = tablaClientes.getSelectedRowCount() > 0;
        if(selected){
            int row = getFilaSeleccionada();
            String rut = getRutFila(row);
            String nombres = getNombresFila(row);
            String apP = getApPaternoFila(row);
            String[] rut_dv = rut.split("-");
            miControlador.irVistaModificarClientes(rut_dv[0], nombres, apP);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un cliente para ser modificado");
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void MenuControlEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlEmpleadosActionPerformed
        this.setVisible(false);
        controladores.controladorPrincipal miControlador = new controladores.controladorPrincipal();
        miControlador.crearControladorEmpleados();
    }//GEN-LAST:event_MenuControlEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new vistaControlClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAgenda;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuCaja;
    private javax.swing.JMenuItem MenuCambioClave;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuCobranza;
    private javax.swing.JMenuItem MenuControlClientes;
    private javax.swing.JMenuItem MenuControlEmpleados;
    private javax.swing.JMenuItem MenuControlGruas;
    private javax.swing.JMenuItem MenuControlUsuarios;
    private javax.swing.JMenu MenuEmpleados;
    private javax.swing.JMenu MenuFacturacion;
    private javax.swing.JMenuItem MenuFiniquitos;
    private javax.swing.JMenuItem MenuGestionAgendas;
    private javax.swing.JMenu MenuGruas;
    private javax.swing.JMenuItem MenuJornadaDiaria;
    private javax.swing.JMenuItem MenuLiquidaciones;
    private javax.swing.JMenu MenuMantenciones;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuUsuarios;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JButton botonAgregarCliente;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables

    public int getFilaSeleccionada() {
        return tablaClientes.getSelectedRow();
    }

    public String getRutFila(int row){
        return tablaClientes.getValueAt(row, 0).toString();
    }
    
    public String getNombresFila(int row){
        return tablaClientes.getValueAt(row,1).toString();
    }
    
    public String getApPaternoFila(int row){
        return tablaClientes.getValueAt(row, 2).toString();
    }
}
