/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas2;

import java.awt.Component;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import modelos2.modeloCompras;
import org.jdesktop.swingx.renderer.DefaultTableRenderer;
import org.jdesktop.swingx.renderer.FormatStringValue;
import org.jdesktop.swingx.renderer.StringValue;
import org.jdesktop.swingx.table.DatePickerCellEditor;

/**
 *
 * @author diego
 */
public class vistaDetalleCompras extends javax.swing.JDialog {

    /**
     * Creates new form vistaDetalleCompra
     */
    StringValue sv = new FormatStringValue(new SimpleDateFormat("dd-MMMM-yyyy"));
    TableCellRenderer r = new DefaultTableRenderer(sv);
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    MyTableModel detalles = new MyTableModel();
    MyTableModelImpuestos impuestos = new MyTableModelImpuestos();
    MyTableModelCheques cheques = new MyTableModelCheques();
    MyTableModelTC tc = new MyTableModelTC();
    public vistaDetalleCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tablaDetalle.setModel(detalles);
        tablaImpuestos.setModel(impuestos);
        tablaDetalle.getColumnModel().getColumn(3).setCellRenderer(new CurrencyTableCellRenderer());
        tablaImpuestos.getColumnModel().getColumn(1).setCellRenderer(new CurrencyTableCellRenderer());
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelTipoDTE = new javax.swing.JLabel();
        comboTipoDTE = new javax.swing.JComboBox();
        labelRut = new javax.swing.JLabel();
        labelRazon = new javax.swing.JLabel();
        textoRazon = new javax.swing.JTextField();
        labelForma = new javax.swing.JLabel();
        comboForma = new javax.swing.JComboBox();
        labelFechaIngreso = new javax.swing.JLabel();
        textoFechaIngreso = new org.jdesktop.swingx.JXDatePicker();
        labelFolio = new javax.swing.JLabel();
        textoFolio = new javax.swing.JTextField();
        labelOrden = new javax.swing.JLabel();
        textoOrden = new javax.swing.JTextField();
        labelFechaPago = new javax.swing.JLabel();
        textoFechaPago = new org.jdesktop.swingx.JXDatePicker();
        labelMedio = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        comboMedio = new javax.swing.JComboBox();
        spinnerCantidad = new javax.swing.JSpinner();
        labelBanco = new javax.swing.JLabel();
        textoBanco = new javax.swing.JTextField();
        scrollDatos = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        labelNumTC = new javax.swing.JLabel();
        textoNumTC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        botonMenos = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        textoAsunto = new javax.swing.JTextField();
        labelAsunto = new javax.swing.JLabel();
        spinnerNumCuotas = new javax.swing.JSpinner();
        labelNumCuotas = new javax.swing.JLabel();
        labelGiro = new javax.swing.JLabel();
        textoGiro = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        labelContacto = new javax.swing.JLabel();
        textoContacto = new javax.swing.JTextField();
        labelObs = new javax.swing.JLabel();
        scrollObs = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        textoRut = new javax.swing.JTextField();
        labelClasificacion = new javax.swing.JLabel();
        comboClasificacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        checkEstado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        textoNeto = new javax.swing.JFormattedTextField(FORMAT);
        jLabel3 = new javax.swing.JLabel();
        textoIva = new javax.swing.JFormattedTextField(FORMAT);
        jLabel4 = new javax.swing.JLabel();
        textoTot = new javax.swing.JFormattedTextField(FORMAT);
        textoImpuestoEsp = new javax.swing.JTextField();
        textoImpuestoVar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkImpuestos = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaImpuestos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        jPanel1.setEnabled(false);

        labelTipoDTE.setText("Tipo de DTE");

        comboTipoDTE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Factura de ventas y servicios", "Factura de venta y servicios electrónica", "Factura exenta", "Factura exenta electrónica", "Nota de crédito", "Nota de crédito electrónica", "Nota de débito", "Nota de débito electrónica" }));
        comboTipoDTE.setEnabled(false);

        labelRut.setText("Rut proveedor");

        labelRazon.setText("Razón social");

        textoRazon.setEditable(false);
        textoRazon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoRazon.setForeground(new java.awt.Color(255, 51, 51));

        textoRazon.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        textoRazon.setEnabled(false);

        labelForma.setText("Forma de pago");

        comboForma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Al día", "30 días", "60 días", "90 días", "Otros pagos" }));
        comboForma.setEnabled(false);

        labelFechaIngreso.setText("Fecha de ingreso");

        textoFechaIngreso.setEnabled(false);

        labelFolio.setText("Folio documento");

        textoFolio.setEditable(false);

        labelOrden.setText("Orden de compra");

        textoOrden.setEditable(false);

        labelFechaPago.setText("Fecha de pago");

        textoFechaPago.setEnabled(false);

        labelMedio.setText("Medio de pago");

        labelCantidad.setText("Cantidad");

        comboMedio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Transferencia", "Cheque", "Tarjeta de crédito" }));
        comboMedio.setEnabled(false);

        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerCantidad.setEnabled(false);

        labelBanco.setText("Banco");

        textoBanco.setEditable(false);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDatos.setEnabled(false);
        scrollDatos.setViewportView(tablaDatos);

        labelNumTC.setText("Número de tarjeta de crédito");

        textoNumTC.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 176));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDetalle.setEnabled(false);
        jScrollPane2.setViewportView(tablaDetalle);

        botonMenos.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        botonMenos.setText("-");
        botonMenos.setEnabled(false);

        botonMas.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        botonMas.setText("+");
        botonMas.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMenos)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenos)
                    .addComponent(botonMas)))
        );

        textoAsunto.setEditable(false);

        labelAsunto.setText("Asunto");

        spinnerNumCuotas.setEnabled(false);

        labelNumCuotas.setText("Número de cuotas");

        labelGiro.setText("Giro");

        textoGiro.setEditable(false);
        textoGiro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoGiro.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelDireccion.setText("Dirección");

        textoDireccion.setEditable(false);
        textoDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoDireccion.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelContacto.setText("Contacto");

        textoContacto.setEditable(false);
        textoContacto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoContacto.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelObs.setText("Observaciones de pago");

        textoObs.setColumns(20);
        textoObs.setRows(5);
        textoObs.setEnabled(false);
        scrollObs.setViewportView(textoObs);

        textoRut.setEditable(false);
        textoRut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoRut.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelClasificacion.setText("Clasificación de compra");

        comboClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo fijo (maquinaria)", "Activo vehiculo", "Combustibles (petróleo/gas)", "Respuestos", "Neumáticos", "Aceite y lubricantes", "Mantenciones", "Gastos de oficina", "Gastos generales", "Arriendo leasing", "Salud y seguridad", "Molymet", "Otros" }));
        comboClasificacion.setEnabled(false);

        jLabel1.setText("Estado");

        checkEstado.setText("Pagada");
        checkEstado.setEnabled(false);

        jLabel2.setText("Neto");

        textoNeto.setEditable(false);

        jLabel3.setText("Iva");

        textoIva.setEditable(false);

        jLabel4.setText("Total");

        textoTot.setEditable(false);

        textoImpuestoEsp.setEditable(false);

        textoImpuestoVar.setEditable(false);

        jLabel5.setText("Impuesto específico");

        jLabel6.setText("Impuesto variable");

        checkImpuestos.setText("Otros impuestos");
        checkImpuestos.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Otros impuestos"));

        tablaImpuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaImpuestos.setEnabled(false);
        jScrollPane3.setViewportView(tablaImpuestos);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("-");
        jButton1.setEnabled(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("+");
        jButton2.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollObs)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollDatos)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboClasificacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoGiro)
                            .addComponent(labelMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoDTE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoContacto)
                            .addComponent(textoBanco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoOrden, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboForma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoAsunto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMedio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelTipoDTE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRut, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBanco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelContacto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textoRut, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoFolio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoNumTC)
                                    .addComponent(spinnerCantidad)
                                    .addComponent(labelRazon)
                                    .addComponent(labelNumTC)
                                    .addComponent(labelFolio)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(textoDireccion))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoRazon)
                                            .addComponent(textoFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textoFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelFechaPago)
                                            .addComponent(labelFechaIngreso)
                                            .addComponent(labelDireccion)
                                            .addComponent(spinnerNumCuotas))
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkEstado)
                                            .addComponent(jLabel1))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGiro)
                            .addComponent(labelOrden)
                            .addComponent(labelForma)
                            .addComponent(labelAsunto)
                            .addComponent(labelObs)
                            .addComponent(labelClasificacion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textoImpuestoEsp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textoNeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoIva, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(textoImpuestoVar))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textoTot))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkImpuestos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoDTE)
                    .addComponent(labelFolio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoDTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRut)
                    .addComponent(labelRazon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGiro)
                    .addComponent(labelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaIngreso)
                    .addComponent(labelContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelClasificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrden)
                    .addComponent(labelFechaPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForma)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAsunto)
                    .addComponent(labelNumCuotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollObs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedio)
                    .addComponent(labelCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBanco)
                    .addComponent(labelNumTC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNumTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoImpuestoEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoImpuestoVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkImpuestos)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jScrollPane1.setViewportView(jPanel1);

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(botonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(botonOK)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        dispose();
    }//GEN-LAST:event_botonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaDetalleCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaDetalleCompras dialog = new vistaDetalleCompras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonOK;
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JCheckBox checkImpuestos;
    private javax.swing.JComboBox<String> comboClasificacion;
    private javax.swing.JComboBox comboForma;
    private javax.swing.JComboBox comboMedio;
    private javax.swing.JComboBox comboTipoDTE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAsunto;
    private javax.swing.JLabel labelBanco;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelClasificacion;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelFechaPago;
    private javax.swing.JLabel labelFolio;
    private javax.swing.JLabel labelForma;
    private javax.swing.JLabel labelGiro;
    private javax.swing.JLabel labelMedio;
    private javax.swing.JLabel labelNumCuotas;
    private javax.swing.JLabel labelNumTC;
    private javax.swing.JLabel labelObs;
    private javax.swing.JLabel labelOrden;
    private javax.swing.JLabel labelRazon;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel labelTipoDTE;
    private javax.swing.JScrollPane scrollDatos;
    private javax.swing.JScrollPane scrollObs;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JSpinner spinnerNumCuotas;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaImpuestos;
    private javax.swing.JTextField textoAsunto;
    private javax.swing.JTextField textoBanco;
    private javax.swing.JTextField textoContacto;
    private javax.swing.JTextField textoDireccion;
    private org.jdesktop.swingx.JXDatePicker textoFechaIngreso;
    private org.jdesktop.swingx.JXDatePicker textoFechaPago;
    private javax.swing.JTextField textoFolio;
    private javax.swing.JTextField textoGiro;
    private javax.swing.JTextField textoImpuestoEsp;
    private javax.swing.JTextField textoImpuestoVar;
    private javax.swing.JFormattedTextField textoIva;
    private javax.swing.JFormattedTextField textoNeto;
    private javax.swing.JTextField textoNumTC;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoOrden;
    private javax.swing.JTextField textoRazon;
    private javax.swing.JTextField textoRut;
    private javax.swing.JFormattedTextField textoTot;
    // End of variables declaration//GEN-END:variables

    public class MyTableModelCheques extends DefaultTableModel{
        public MyTableModelCheques() {
          super(new String[]{"Cheque", "Folio", "Fecha vencimiento", "Monto", "Estado"}, 0);
        }
        
        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
                return Integer.class;
            case 1: 
                return Integer.class;
            case 2:
                return Date.class;
            case 3: 
                return Integer.class;
            default:
                return Boolean.class;
          }
        }
    }
    
    public class MyTableModelTC extends DefaultTableModel{
        public MyTableModelTC() {
          super(new String[]{"Cuota", "Fecha vencimiento", "Monto", "Estado"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
                return Integer.class;
            case 1: 
                return Date.class;
            case 2:
                return Integer.class;
            default:
                return Boolean.class;
          }
        }
    }
    
    public class MyTableModel extends DefaultTableModel{
        public MyTableModel() {
          super(new String[]{"Código del producto", "Detalle", "Cantidad", "Precio Unitario", "Iva"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
                return Integer.class;
            case 1: 
                return String.class;
            case 2:
                return Double.class;
            case 3: 
                return Double.class;
            default:
                return Boolean.class;
          }
        }
    }
    
    public class MyTableModelImpuestos extends DefaultTableModel{
        public MyTableModelImpuestos() {
          super(new String[]{"Nombre del impuesto", "Monto"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
                return String.class;
            default:
                return Integer.class;
          }
        }
    }
    
    public void setComboForma(String comboForma) {
        this.comboForma.setSelectedItem(comboForma);
    }

    public void setComboMedio(String comboMedio) {
        this.comboMedio.setSelectedItem(comboMedio);
    }

    public void setTextoRut(String textoRut) {
        this.textoRut.setText(textoRut);
    }

    public void setComboTipoDTE(String comboTipoDTE) {
        this.comboTipoDTE.setSelectedItem(comboTipoDTE);
    }

    public void setSpinnerCantidad(String spinnerCantidad) {
        this.spinnerCantidad.setValue(Integer.parseInt(spinnerCantidad));
    }

    public void setSpinnerNumCuotas(String spinnerNumCuotas) {
        this.spinnerNumCuotas.setValue(Integer.parseInt(spinnerNumCuotas));
    }

    public void setTextoBanco(String textoBanco) {
        this.textoBanco.setText(textoBanco);
    }

    public void setTextoContacto(String textoContacto) {
        this.textoContacto.setText(textoContacto);
    }

    public void setTextoDireccion(String textoDireccion) {
        this.textoDireccion.setText(textoDireccion);
    }

    public void setTextoFechaIngreso(String textoFechaIngreso) throws ParseException {
        this.textoFechaIngreso.setDate(formatDate.parse(textoFechaIngreso));
    }

    public void setTextoFechaPago(String textoFechaPago) throws ParseException {
        this.textoFechaPago.setDate(formatDate.parse(textoFechaPago));
    }

    public void setTextoFolio(String textoFolio) {
        this.textoFolio.setText(textoFolio);
    }

    public void setTextoGiro(String textoGiro) {
        this.textoGiro.setText(textoGiro);
    }

    public void setTextoNumTC(String textoNumTC) {
        this.textoNumTC.setText(textoNumTC);
    }

    public void setTextoObs(String textoObs) {
        this.textoObs.setText(textoObs);
    }

    public void setTextoOrden(String textoOrden) {
        this.textoOrden.setText(textoOrden);
    }

    public void setTextoRazon(String textoRazon) {
        this.textoRazon.setText(textoRazon);
    }

    public void setTextoAsunto(String textoAsunto) {
        this.textoAsunto.setText(textoAsunto);
    }
    
    public void setComboClas(String comboClas){
        this.comboClasificacion.setSelectedItem(comboClas);
    }
    
    public void setTextoNeto(String textoTot){
        this.textoNeto.setValue(Integer.parseInt(textoTot));
    }
    
    public void setTextoIva(String textoIva){
        this.textoIva.setValue(Integer.parseInt(textoIva));
    }
    
    public void setTextoImpuestoEsp(String val){
        try{
            Object value = Integer.parseInt(val);
            if (value instanceof Number) {
                textoImpuestoEsp.setHorizontalAlignment(JLabel.RIGHT);
                textoImpuestoEsp.setText(FORMAT.format(value));
            } else {
                textoImpuestoEsp.setHorizontalAlignment(JLabel.RIGHT);
                textoImpuestoEsp.setText("");
            }
        }catch(NumberFormatException e){
            textoImpuestoEsp.setHorizontalAlignment(JLabel.RIGHT);
            textoImpuestoEsp.setText("");
        }
    
    }
    
    public void setTextoImpuestoVar(String val){
        try{
            Object value = Integer.parseInt(val);
            if (value instanceof Number) {
                textoImpuestoVar.setHorizontalAlignment(JLabel.RIGHT);
                textoImpuestoVar.setText(FORMAT.format(value));
            } else {
                textoImpuestoVar.setHorizontalAlignment(JLabel.RIGHT);
                textoImpuestoVar.setText("");
            }
        }catch(NumberFormatException e){
            textoImpuestoVar.setHorizontalAlignment(JLabel.RIGHT);
            textoImpuestoVar.setText("");
        }
    }
    
    public void setTextoTot(String textoNeto){
        this.textoTot.setValue(Integer.parseInt(textoNeto));
    }
    
    public void setCheckEstado(String checkEstado){
        if(checkEstado.compareTo("Pagado") == 0){
            this.checkEstado.setSelected(true);
        }else{
            this.checkEstado.setSelected(false);
        }
    }
    
    public class CurrencyTableCellRenderer extends DefaultTableCellRenderer {
        @Override
        public final Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
                final Component result = super.getTableCellRendererComponent(table, value,
                    isSelected, hasFocus, row, column);
                if (value instanceof Number) {
                    setHorizontalAlignment(JLabel.RIGHT);
                    setText(FORMAT.format(value));
                } else {
                    setText("");
                }
                return result;
        }
    }
    
    final public void hideOtrosPagos(){
        labelAsunto.setVisible(false);
        labelNumCuotas.setVisible(false);
        labelObs.setVisible(false);
        textoAsunto.setVisible(false);
        spinnerNumCuotas.setVisible(false);
        scrollObs.setVisible(false);
    }
    
    final public void hideMedioPago(){
        labelCantidad.setVisible(false);
        spinnerCantidad.setVisible(false);
        labelBanco.setVisible(false);
        textoBanco.setVisible(false);
        labelNumTC.setVisible(false);
        textoNumTC.setVisible(false);
        scrollDatos.setVisible(false);
    }
    
    final public void showCheques(String id) throws ParseException{
        labelCantidad.setText("Cantidad de cheques");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerChequesPorId(id);
        cheques.setRowCount(data.length);
        tablaDatos.setModel(cheques);
        //TableColumn column = tablaDatos.getColumnModel().getColumn(2);
//        column.setCellEditor(new DatePickerCellEditor());
        tablaDatos.getColumnModel().getColumn(3).setCellRenderer(new CurrencyTableCellRenderer());
        agregarCheques(data);
        scrollDatos.setVisible(true);
        spinnerCantidad.setValue(data.length);
        spinnerNumCuotas.setValue(data.length);
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(false);
        textoNumTC.setVisible(false);
    }
    
    public void agregarCheques(Object[][] data) throws ParseException{
        int i = 0;
        for(Object[] data1 : data){
            Date date = formatDate.parse(data1[2].toString());
            boolean flag = data1[4].toString().compareTo("Pagado") == 0;
            tablaDatos.setValueAt(data1[0], i, 0);
            tablaDatos.setValueAt(data1[1], i, 1);
            tablaDatos.setValueAt(date, i, 2);
            tablaDatos.setValueAt(Integer.parseInt(data1[3].toString()), i, 3);
            tablaDatos.setValueAt(flag, i, 4);
            i++;
        }
    }
    
    public void agregarProductos(String id) throws ParseException{
        int i = 0;
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerProductosPorId(id);
        detalles.setRowCount(data.length);
        for(Object[] data1 : data){
            boolean flag = data1[4].toString().compareTo("1") == 0;
            tablaDetalle.setValueAt(data1[0], i, 0);
            tablaDetalle.setValueAt(data1[1], i, 1);
            tablaDetalle.setValueAt(Double.parseDouble(data1[2].toString()), i, 2);
            tablaDetalle.setValueAt(Double.parseDouble(data1[3].toString()), i, 3);
            tablaDetalle.setValueAt(flag, i, 4);
            i++;
        }
    }
    
    public void agregarImpuestos(String id) throws ParseException{
        int i = 0;
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerImpuestosPorId(id);
        impuestos.setRowCount(data.length);
        if(data.length > 0) checkImpuestos.setSelected(true);
        for(Object[] data1 : data){
            tablaImpuestos.setValueAt(data1[0], i, 0);
            tablaImpuestos.setValueAt(Integer.parseInt(data1[1].toString()), i, 1);
            i++;
        }
    }
    
    final public void showTC(String id) throws ParseException{
        labelCantidad.setText("Número de cuotas");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerCuotasPorId(id);
        tc.setRowCount(data.length);
        tablaDatos.setModel(tc);
        tablaDatos.getColumnModel().getColumn(2).setCellRenderer(new CurrencyTableCellRenderer());
        agregarCuotas(data);
//        TableColumn column = tablaDatos.getColumnModel().getColumn(1);
//        column.setCellEditor(new DatePickerCellEditor());
        scrollDatos.setVisible(true);
        spinnerCantidad.setValue(data.length);
        spinnerNumCuotas.setValue(data.length);
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(true);
        textoNumTC.setVisible(true);
    }
    
    final public void showTR(String id) throws ParseException{
        labelCantidad.setText("Número de cuotas");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerCuotasPorId(id);
        tc.setRowCount(data.length);
        tablaDatos.setModel(tc);
        tablaDatos.getColumnModel().getColumn(2).setCellRenderer(new CurrencyTableCellRenderer());
        agregarCuotas(data);
//        TableColumn column = tablaDatos.getColumnModel().getColumn(1);
//        column.setCellEditor(new DatePickerCellEditor());
        scrollDatos.setVisible(true);
        spinnerCantidad.setValue(data.length);
        spinnerNumCuotas.setValue(data.length);
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(true);
        textoNumTC.setVisible(true);
    }
    
    public void agregarCuotas(Object[][] data) throws ParseException{
        int i = 0;
        for(Object[] data1 : data){
            Date date = formatDate.parse(data1[1].toString());
            boolean flag = data1[3].toString().compareTo("Pagado") == 0;
            tablaDatos.setValueAt(data1[0], i, 0);
            tablaDatos.setValueAt(date, i, 1);
            tablaDatos.setValueAt(Integer.parseInt(data1[2].toString()), i, 2);
            tablaDatos.setValueAt(flag, i, 3);
            i++;
        }
    }
}
