/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas2;

import controladores2.controladorIngresarCompras;
import controladores2.controladorModificarCompras;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.text.JTextComponent;
import modelos2.modeloCompras;
import modelos2.modeloProveedores;
import org.jdesktop.swingx.renderer.DefaultTableRenderer;
import org.jdesktop.swingx.renderer.FormatStringValue;
import org.jdesktop.swingx.renderer.StringValue;
import org.jdesktop.swingx.table.DatePickerCellEditor;

/**
 *
 * @author diego
 */
public class vistaModificarCompras extends javax.swing.JDialog {
    
    String id;
    modelos2.modeloProveedores proveedor = new modeloProveedores();
    StringValue sv = new FormatStringValue(new SimpleDateFormat("dd-MMMM-yyyy"));
    TableCellRenderer r = new DefaultTableRenderer(sv);
    NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
    List<String> listProveedores = new ArrayList<>();
    JTextField textoRut = new JTextField();
    DefaultTableModel datos;
    MyTableModelCheques cheques = new MyTableModelCheques();
    MyTableModelTC tc = new MyTableModelTC();
    MyTableModel detalles = new MyTableModel();
    private boolean hide_flag = false;
    
    public vistaModificarCompras(java.awt.Frame parent, boolean modal, Object proveedores[]) {
        super(parent, modal);
        initComponents();
        dfs.setCurrencySymbol("$");
        dfs.setGroupingSeparator('.');
        dfs.setMonetaryDecimalSeparator('.');
        ((DecimalFormat) FORMAT).setDecimalFormatSymbols(dfs);
        textoRut = (JTextField)comboRut.getEditor().getEditorComponent();
        final JTextComponent tcr = (JTextComponent) comboRut.getEditor().getEditorComponent();
        tcr.getDocument().addDocumentListener(new DocumentListener() { 
            @Override
            public void insertUpdate(DocumentEvent de) {
                String data[] = proveedor.obtenerProveedorPorRut(comboRut.getSelectedItem().toString());
                setTextoContacto(data[2]);
                setTextoRazon(data[3]);
                setTextoGiro(data[4]);
                setTextoDireccion(data[7]);
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
            }
        });
        tablaDetalle.setModel(detalles);
        tablaDetalle.getColumnModel().getColumn(3).setCellRenderer(new CurrencyTableCellRenderer());
        autosuggestProveedores(proveedores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelTipoDTE = new javax.swing.JLabel();
        comboTipoDTE = new javax.swing.JComboBox();
        labelRut = new javax.swing.JLabel();
        comboRut = new javax.swing.JComboBox();
        labelRazon = new javax.swing.JLabel();
        textoRazon = new javax.swing.JTextField();
        labelForma = new javax.swing.JLabel();
        comboForma = new javax.swing.JComboBox();
        labelFechaIngreso = new javax.swing.JLabel();
        textoFechaIngreso = new org.jdesktop.swingx.JXDatePicker();
        labelFolio = new javax.swing.JLabel();
        textoFolio = new javax.swing.JTextField();
        labelOrden = new javax.swing.JLabel();
        textoOrden = new javax.swing.JTextField();
        labelFechaPago = new javax.swing.JLabel();
        textoFechaPago = new org.jdesktop.swingx.JXDatePicker();
        labelMedio = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        comboMedio = new javax.swing.JComboBox();
        spinnerCantidad = new javax.swing.JSpinner();
        labelBanco = new javax.swing.JLabel();
        textoBanco = new javax.swing.JTextField();
        scrollDatos = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        labelNumTC = new javax.swing.JLabel();
        textoNumTC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        botonMenos = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        textoAsunto = new javax.swing.JTextField();
        labelAsunto = new javax.swing.JLabel();
        spinnerNumCuotas = new javax.swing.JSpinner();
        labelNumCuotas = new javax.swing.JLabel();
        labelGiro = new javax.swing.JLabel();
        textoGiro = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        labelContacto = new javax.swing.JLabel();
        textoContacto = new javax.swing.JTextField();
        labelObs = new javax.swing.JLabel();
        scrollObs = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        comboClasificacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        checkEstado = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        textoTot = new javax.swing.JFormattedTextField(FORMAT);
        jLabel4 = new javax.swing.JLabel();
        textoIva = new javax.swing.JFormattedTextField(FORMAT);
        jLabel5 = new javax.swing.JLabel();
        textoNeto = new javax.swing.JFormattedTextField(FORMAT);
        jButton1 = new javax.swing.JButton();
        botonOK = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTipoDTE.setText("Tipo de DTE");

        comboTipoDTE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Factura de ventas y servicios", "Factura de venta y servicios electrónica", "Factura exenta", "Factura exenta electrónica", "Nota de crédito", "Nota de crédito electrónica", "Nota de débito", "Nota de débito electrónica" }));

        labelRut.setText("Rut proveedor");

        labelRazon.setText("Razón social");

        textoRazon.setEditable(false);
        textoRazon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoRazon.setForeground(new java.awt.Color(255, 51, 51));

        textoRazon.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        textoRazon.setEnabled(false);

        labelForma.setText("Forma de pago");

        comboForma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Al día", "30 días", "60 días", "90 días", "Otros pagos" }));
        comboForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormaActionPerformed(evt);
            }
        });

        labelFechaIngreso.setText("Fecha de ingreso");

        labelFolio.setText("Folio documento");

        labelOrden.setText("Orden de compra");

        labelFechaPago.setText("Fecha de pago");

        labelMedio.setText("Medio de pago");

        labelCantidad.setText("Cantidad");

        comboMedio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Transferencia", "Cheque", "Tarjeta de crédito" }));
        comboMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedioActionPerformed(evt);
            }
        });

        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCantidadStateChanged(evt);
            }
        });

        labelBanco.setText("Banco");

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollDatos.setViewportView(tablaDatos);

        labelNumTC.setText("Número de tarjeta de crédito");

        textoNumTC.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 176));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaDetalle);

        botonMenos.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        botonMenos.setText("-");
        botonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosActionPerformed(evt);
            }
        });

        botonMas.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        botonMas.setText("+");
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMenos)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenos)
                    .addComponent(botonMas)))
        );

        labelAsunto.setText("Asunto");

        labelNumCuotas.setText("Número de cuotas");

        labelGiro.setText("Giro");

        textoGiro.setEditable(false);
        textoGiro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoGiro.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelDireccion.setText("Dirección");

        textoDireccion.setEditable(false);
        textoDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoDireccion.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelContacto.setText("Contacto");

        textoContacto.setEditable(false);
        textoContacto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoContacto.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        labelObs.setText("Observaciones de pago");

        textoObs.setColumns(20);
        textoObs.setRows(5);
        scrollObs.setViewportView(textoObs);

        jLabel1.setText("Clasificación de compra");

        comboClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo fijo (maquinaria)", "Activo vehiculo", "Combustibles (petróleo/gas)", "Respuestos", "Neumáticos", "Aceite y lubricantes", "Mantenciones", "Gastos de oficina", "Gastos generales", "Arriendo leasing", "Salud y seguridad", "Molymet", "Otros" }));

        jLabel2.setText("Estado");

        checkEstado.setText("Pagada");

        jLabel3.setText("Total");

        jLabel4.setText("Iva");

        jLabel5.setText("Neto");

        jButton1.setText("Actualizar montos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollObs)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollDatos)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboClasificacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoGiro)
                            .addComponent(labelMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoDTE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoContacto)
                            .addComponent(textoBanco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoOrden, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboRut, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboForma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoAsunto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMedio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelTipoDTE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRut, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBanco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelContacto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoFolio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoNumTC)
                                    .addComponent(spinnerCantidad)
                                    .addComponent(labelRazon)
                                    .addComponent(labelNumTC)
                                    .addComponent(labelFolio)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(textoDireccion))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoRazon)
                                            .addComponent(textoFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textoFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelFechaPago)
                                            .addComponent(labelFechaIngreso)
                                            .addComponent(labelDireccion)
                                            .addComponent(spinnerNumCuotas))
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkEstado)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGiro)
                            .addComponent(labelOrden)
                            .addComponent(labelForma)
                            .addComponent(labelAsunto)
                            .addComponent(labelObs)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(textoTot))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(textoIva, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoDTE)
                    .addComponent(labelFolio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoDTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRut)
                    .addComponent(labelRazon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGiro)
                    .addComponent(labelDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaIngreso)
                    .addComponent(labelContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrden)
                    .addComponent(labelFechaPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForma)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAsunto)
                    .addComponent(labelNumCuotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollObs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedio)
                    .addComponent(labelCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBanco)
                    .addComponent(labelNumTC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNumTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textoIva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );

        jScrollPane1.setViewportView(jPanel1);

        botonOK.setText("Cancelar");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(607, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAceptar, botonOK});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(571, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOK)
                    .addComponent(botonAceptar))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGap(46, 46, 46)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCantidadStateChanged
        if(comboMedio.getSelectedIndex() == 2){
            cheques.setRowCount(Integer.parseInt(spinnerCantidad.getValue().toString()));
            for(int i = 0; i < Integer.parseInt(spinnerCantidad.getValue().toString()); i++){
                cheques.setValueAt(i+1, i, 0);
            }
            tablaDatos.setModel(cheques);
        }else{
            tc.setRowCount(Integer.parseInt(spinnerCantidad.getValue().toString()));
            for(int i = 0; i < Integer.parseInt(spinnerCantidad.getValue().toString()); i++){
                tc.setValueAt(i+1, i, 0);
            }
            tablaDatos.setModel(tc);
        }
    }//GEN-LAST:event_spinnerCantidadStateChanged

    private void botonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosActionPerformed
        if(detalles.getRowCount() > 0){
            detalles.setRowCount(detalles.getRowCount()-1);
            tablaDetalle.setModel(detalles);
        }  
    }//GEN-LAST:event_botonMenosActionPerformed

    private void botonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasActionPerformed
        detalles.setRowCount(detalles.getRowCount()+1);
        tablaDetalle.setModel(detalles);
    }//GEN-LAST:event_botonMasActionPerformed

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        dispose();
    }//GEN-LAST:event_botonOKActionPerformed

    private void comboMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedioActionPerformed
        switch(comboMedio.getSelectedIndex()){
            case 2:
                showCheques();
                break;
            case 3:
                showTC();
                break;
            default:
                hideMedioPago();
        }
    }//GEN-LAST:event_comboMedioActionPerformed

    private void comboFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormaActionPerformed
        if(comboForma.getSelectedIndex() == 4){
            showOtrosPagos();
        }else{
            hideOtrosPagos();
        }
    }//GEN-LAST:event_comboFormaActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        controladorModificarCompras miControladorMC = new controladorModificarCompras();
        String respuesta = miControladorMC.camposVacios();
        boolean esVacio = respuesta.length() == 0;
        if (!esVacio) {
            JOptionPane.showMessageDialog(this, respuesta, "Debe rellenar los siguientes campos", JOptionPane.INFORMATION_MESSAGE);
        } else {            
                if (miControladorMC.irVistaComprasP()) {
                    JOptionPane.showMessageDialog(this, "Compra modificada con éxito", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                }            
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calTotales();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaModificarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaModificarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaModificarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaModificarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonOK;
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JComboBox<String> comboClasificacion;
    private javax.swing.JComboBox comboForma;
    private javax.swing.JComboBox comboMedio;
    private javax.swing.JComboBox comboRut;
    private javax.swing.JComboBox comboTipoDTE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAsunto;
    private javax.swing.JLabel labelBanco;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelFechaPago;
    private javax.swing.JLabel labelFolio;
    private javax.swing.JLabel labelForma;
    private javax.swing.JLabel labelGiro;
    private javax.swing.JLabel labelMedio;
    private javax.swing.JLabel labelNumCuotas;
    private javax.swing.JLabel labelNumTC;
    private javax.swing.JLabel labelObs;
    private javax.swing.JLabel labelOrden;
    private javax.swing.JLabel labelRazon;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel labelTipoDTE;
    private javax.swing.JScrollPane scrollDatos;
    private javax.swing.JScrollPane scrollObs;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JSpinner spinnerNumCuotas;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTextField textoAsunto;
    private javax.swing.JTextField textoBanco;
    private javax.swing.JTextField textoContacto;
    private javax.swing.JTextField textoDireccion;
    private org.jdesktop.swingx.JXDatePicker textoFechaIngreso;
    private org.jdesktop.swingx.JXDatePicker textoFechaPago;
    private javax.swing.JTextField textoFolio;
    private javax.swing.JTextField textoGiro;
    private javax.swing.JFormattedTextField textoIva;
    private javax.swing.JFormattedTextField textoNeto;
    private javax.swing.JTextField textoNumTC;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoOrden;
    private javax.swing.JTextField textoRazon;
    private javax.swing.JFormattedTextField textoTot;
    // End of variables declaration//GEN-END:variables
    
    public void setComboForma(String comboForma) {
        this.comboForma.setSelectedItem(comboForma);
    }

    public void setComboMedio(String comboMedio) {
        this.comboMedio.setSelectedItem(comboMedio);
    }

    public void setComboRut(String comboRut) {
        this.comboRut.setSelectedItem(comboRut);
    }

    public void setComboTipoDTE(String comboTipoDTE) {
        this.comboTipoDTE.setSelectedItem(comboTipoDTE);
    }

    public void setSpinnerCantidad(String spinnerCantidad) {
        this.spinnerCantidad.setValue(Integer.parseInt(spinnerCantidad));
    }

    public void setSpinnerNumCuotas(String spinnerNumCuotas) {
        this.spinnerNumCuotas.setValue(Integer.parseInt(spinnerNumCuotas));
    }

    public void setTextoBanco(String textoBanco) {
        this.textoBanco.setText(textoBanco);
    }

    public void setTextoContacto(String textoContacto) {
        this.textoContacto.setText(textoContacto);
    }

    public void setTextoDireccion(String textoDireccion) {
        this.textoDireccion.setText(textoDireccion);
    }

    public void setTextoFechaIngreso(String textoFechaIngreso) throws ParseException {
        this.textoFechaIngreso.setDate(formatDate.parse(textoFechaIngreso));
    }

    public void setTextoFechaPago(String textoFechaPago) throws ParseException {
        this.textoFechaPago.setDate(formatDate.parse(textoFechaPago));
    }

    public void setTextoFolio(String textoFolio) {
        this.textoFolio.setText(textoFolio);
    }

    public void setTextoGiro(String textoGiro) {
        this.textoGiro.setText(textoGiro);
    }

    public void setTextoNumTC(String textoNumTC) {
        this.textoNumTC.setText(textoNumTC);
    }

    public void setTextoObs(String textoObs) {
        this.textoObs.setText(textoObs);
    }

    public void setTextoOrden(String textoOrden) {
        this.textoOrden.setText(textoOrden);
    }

    public void setTextoRazon(String textoRazon) {
        this.textoRazon.setText(textoRazon);
    }

    public void setTextoAsunto(String textoAsunto) {
        this.textoAsunto.setText(textoAsunto);
    }
    
    public void setComboClas(String comboClas){
        this.comboClasificacion.setSelectedItem(comboClas);
    }
    
    public void setTextoTot(String textoTot){
        this.textoTot.setValue(Integer.parseInt(textoTot));
    }
    
    public void setTextoIva(String textoIva){
        this.textoIva.setValue(Integer.parseInt(textoIva));
    }
    
    public void setTextoNeto(String textoNeto){
        this.textoNeto.setValue(Integer.parseInt(textoNeto));
    }
    
    public void setCheckEstado(String checkEstado){
        if(checkEstado.compareTo("Pagado") == 0){
            this.checkEstado.setSelected(true);
        }else{
            this.checkEstado.setSelected(false);
        }
    }
    
    public String getComboForma() {
        return comboForma.getSelectedItem().toString();
    }

    public String getComboMedio() {
        return comboMedio.getSelectedItem().toString();
    }

    public String getComboRut() {
        return comboRut.getSelectedItem().toString();
    }

    public String getComboTipoDTE() {
        return comboTipoDTE.getSelectedItem().toString();
    }

    public String getTextoAsunto() {
        if(comboForma.getSelectedIndex() == 4){
            return textoAsunto.getText();
        }else{
            return "";
        }
    }

    public String getTextoBanco() {
        return textoBanco.getText();
    }
    
    public String getTextoNumTC(){
        return textoNumTC.getText();
    }

    public String getTextoFechaIngreso() {
        Date fecha = textoFechaIngreso.getDate();
        if (fecha == null) return "";
        String dateString = formatDate.format(textoFechaIngreso.getDate());
        return dateString;
    }

    public String getTextoFechaPago() {
        Date fecha = textoFechaPago.getDate();
        if (fecha == null) return "";
        String dateString = formatDate.format(textoFechaPago.getDate());
        return dateString;
    }

    public String getTextoFolio() {
        return textoFolio.getText();
    }

    public String getTextoObs() {
        if(comboForma.getSelectedIndex() == 4){
            return textoObs.getText();
        }else{
            return "";
        }
    }

    public String getTextoOrden() {
        return textoOrden.getText();
    }
    
    public int getSpinnerCant(){
        return Integer.parseInt(spinnerCantidad.getValue().toString());
    }
    
    public String getComboClas(){
        return comboClasificacion.getSelectedItem().toString();
    }
    
    public String getTextoTot(){
        return textoTot.getValue().toString();
    }
    
    public String getTextoIva(){
        return textoIva.getValue().toString();
    }
    
    public String getTextoNeto(){
        return textoNeto.getValue().toString();
    }
    
    public String getCheckEstado(){
        if(!checkEstado.isEnabled()) return "No pagado";
        if(checkEstado.isSelected()) return "Pagado";
        return "No pagado";
    }
    
    public int getCuotas(){
        switch(comboMedio.getSelectedIndex()){
            case 2:
                return 1;
            case 3:
                return 2;
            default:
                return 0;
        }
    }
    
    public JTable getTablaCuotas(){
        return tablaDatos;
    }
    
    public String getEstadoTablaCheques(int row){
        if(tablaDatos.getValueAt(row, 4) == null || (Boolean)tablaDatos.getValueAt(row, 4) == false){
            return "No pagado";
        }else{
            return "Pagado";
        }
    }
    
    public String getEstadoTablaTC(int row){
        if(tablaDatos.getValueAt(row, 3) == null || (Boolean)tablaDatos.getValueAt(row, 3) == false){
            return "No pagado";
        }else{
            return "Pagado";
        }
    }
    
    public String getfechaTablaCheques(int row){
        Date fecha = (Date)tablaDatos.getValueAt(row, 2);
        if (fecha == null) return "";
        String dateString = formatDate.format(fecha);
        return dateString;
    }
    
    public String getfechaTablaTC(int row){
        Date fecha = (Date)tablaDatos.getValueAt(row, 1);
        if (fecha == null) return "";
        String dateString = formatDate.format(fecha);
        return dateString;
    }
    
    final public void showCheques(){
        labelCantidad.setText("Cantidad de cheques");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        cheques.setRowCount(Integer.parseInt(spinnerCantidad.getValue().toString()));
        for(int i = 0; i < Integer.parseInt(spinnerCantidad.getValue().toString()); i++){
            cheques.setValueAt(i+1, i, 0);
        }
        tablaDatos.setModel(cheques);
        TableColumn column = tablaDatos.getColumnModel().getColumn(2);
        column.setCellEditor(new DatePickerCellEditor());
        tablaDatos.getColumnModel().getColumn(3).setCellRenderer(new CurrencyTableCellRenderer());
        scrollDatos.setVisible(true);
        spinnerCantidad.setValue(spinnerNumCuotas.getValue());
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(false);
        textoNumTC.setVisible(false);
    }
    
    final public void hideOtrosPagos(){
        labelAsunto.setVisible(false);
        labelNumCuotas.setVisible(false);
        labelObs.setVisible(false);
        textoAsunto.setVisible(false);
        spinnerNumCuotas.setVisible(false);
        scrollObs.setVisible(false);
    }

    final public void showTC(){
        labelCantidad.setText("Número de cuotas");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        tc.setRowCount(Integer.parseInt(spinnerCantidad.getValue().toString()));
        for(int i = 0; i < Integer.parseInt(spinnerCantidad.getValue().toString()); i++){
            tc.setValueAt(i+1, i, 0);
        }
        tablaDatos.setModel(tc);
        TableColumn column = tablaDatos.getColumnModel().getColumn(1);
        column.setCellEditor(new DatePickerCellEditor());
        scrollDatos.setVisible(true);
        spinnerCantidad.setValue(spinnerNumCuotas.getValue());
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(true);
        textoNumTC.setVisible(true);
    }
    
    final public void showOtrosPagos(){
        labelAsunto.setVisible(true);
        labelNumCuotas.setVisible(true);
        labelObs.setVisible(true);
        textoAsunto.setVisible(true);
        spinnerNumCuotas.setVisible(true);
        scrollObs.setVisible(true);
    }
    
    final public void hideMedioPago(){
        labelCantidad.setVisible(false);
        spinnerCantidad.setVisible(false);
        labelBanco.setVisible(false);
        textoBanco.setVisible(false);
        labelNumTC.setVisible(false);
        textoNumTC.setVisible(false);
        scrollDatos.setVisible(false);
    }
    
    final public void showCheques(String id) throws ParseException{
        labelCantidad.setText("Cantidad de cheques");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerChequesPorId(id);
        spinnerCantidad.setValue(data.length);
        cheques.setRowCount(Integer.parseInt(spinnerCantidad.getValue().toString()));
        for(int i = 0; i < Integer.parseInt(spinnerCantidad.getValue().toString()); i++){
            cheques.setValueAt(i+1, i, 0);
        }
        tablaDatos.setModel(cheques);
        agregarCheques(data);
        scrollDatos.setVisible(true);
        spinnerNumCuotas.setValue(data.length);
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(false);
        textoNumTC.setVisible(false);
    }
    
    final public void showTC(String id) throws ParseException{
        labelCantidad.setText("Número de cuotas");
        labelCantidad.setVisible(true);
        spinnerCantidad.setVisible(true);
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerCuotasPorId(id);
        tablaDatos.setModel(tc);
        TableColumn column = tablaDatos.getColumnModel().getColumn(1);
        column.setCellEditor(new DatePickerCellEditor());
        spinnerCantidad.setValue(data.length);
        tc.setRowCount(Integer.parseInt(spinnerCantidad.getValue().toString()));
        for(int i = 0; i < Integer.parseInt(spinnerCantidad.getValue().toString()); i++){
            tc.setValueAt(i+1, i, 0);
        }
        tablaDatos.setModel(tc);
        agregarCuotas(data);
        scrollDatos.setVisible(true);
        spinnerNumCuotas.setValue(data.length);
        labelBanco.setVisible(true);
        textoBanco.setVisible(true);
        labelNumTC.setVisible(true);
        textoNumTC.setVisible(true);
    }

    private void setModel(DefaultComboBoxModel mdl, String str, JComboBox combo, JTextField texto){
        combo.setModel(mdl);
        texto.setText(str);
    }

    private DefaultComboBoxModel getSuggestedModel(List<String> list, String tx){
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String s : list){
            if(s.toLowerCase().contains(tx.toLowerCase())){
                m.addElement(s);
            }
        }
        return m;
    }
    
    public final void autosuggestProveedores(Object[] data){
            comboRut.removeAllItems();
            if(comboRut.getItemCount() == 0){
                for (Object data1 : data) {
                    comboRut.addItem(data1);
                    listProveedores.add((String) data1);
                    comboRut.addItemListener(new ItemListener() {

                        @Override
                        public void itemStateChanged(ItemEvent ie) {
                            if(ie.getStateChange() == ItemEvent.SELECTED){
                                comboRut.getSelectedIndex();
                            }
                        }
                    });
                }
            }else{
                comboRut.addItem("Error");
            }

        comboRut.setEditable(true);
        textoRut.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent e){
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        String text = textoRut.getText();
                        if(text.length() == 0){
                            comboRut.hidePopup();
                            setModel(new DefaultComboBoxModel(listProveedores.toArray()), "", comboRut, textoRut);
                        }else{
                            DefaultComboBoxModel m = getSuggestedModel(listProveedores, text);
                            if(m.getSize() == 0){
                                comboRut.hidePopup();
                            }else{
                                setModel(m, text, comboRut, textoRut);
                                comboRut.showPopup();
                            }
                        }
                    }
                });
            }

            @Override
            public void keyPressed(KeyEvent e){
                String text = textoRut.getText();
                int code = e.getKeyCode();
                if(code == KeyEvent.VK_ENTER){
                    for (int i = 0; i < listProveedores.size(); i++) {
                        String str = (String)listProveedores.get(i);
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoRut.setText(str);
                            return;
                        }
                    }
                }else if(code == KeyEvent.VK_ESCAPE){
                    hide_flag = true;
                }else if(code == KeyEvent.VK_RIGHT){
                    for (String listProveedore : listProveedores) {
                        String str = (String) listProveedore;
                        if(str.toLowerCase().contains(text.toLowerCase())){
                            textoRut.setText(str);
                            return;
                        }
                    }
                }
            }
        });
    }
    
    public class MyTableModel extends DefaultTableModel{
        public MyTableModel() {
          super(new String[]{"Código del producto", "Detalle", "Cantidad", "Precio Unitario", "Iva"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
              return Integer.class;
            case 1: 
                return String.class;
            case 2:
                return Integer.class;
            case 3: 
                return Integer.class;
            default:
                return Boolean.class;
          }
        }
    }

    public class MyTableModelCheques extends DefaultTableModel{
        public MyTableModelCheques() {
          super(new String[]{"Cheque", "Folio", "Fecha vencimiento", "Monto", "Estado"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
                return Integer.class;
            case 1: 
                return Integer.class;
            case 2:
                return Date.class;
            case 3: 
                return Integer.class;
            default:
                return Boolean.class;
          }
        }
    }
    
    public class MyTableModelTC extends DefaultTableModel{
        public MyTableModelTC() {
          super(new String[]{"Cuota", "Fecha vencimiento", "Monto", "Estado"}, 0);
        }

        @Override
        public Class getColumnClass(int column) {
          switch (column) {
            case 0:
                return Integer.class;
            case 1: 
                return Date.class;
            case 2:
                return Integer.class;
            default:
                return Boolean.class;
          }
        }
    }
    
    public class CurrencyTableCellRenderer extends DefaultTableCellRenderer {
        @Override
        public final Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            final Component result = super.getTableCellRendererComponent(table, value,
                    isSelected, hasFocus, row, column);
            if (value instanceof Number) {
                setHorizontalAlignment(JLabel.RIGHT);
                setText(FORMAT.format(value));
            } else {
                setText("");
            }
            return result;
        }
    }
    
    public void agregarCheques(Object[][] data) throws ParseException{
        int i = 0;
        for(Object[] data1 : data){
            Date date = formatDate.parse(data1[2].toString());
            boolean flag = data1[4].toString().compareTo("Pagado") == 0;
            tablaDatos.setValueAt(data1[0], i, 0);
            tablaDatos.setValueAt(data1[1], i, 1);
            tablaDatos.setValueAt(date, i, 2);
            tablaDatos.setValueAt(Integer.parseInt(data1[3].toString()), i, 3);
            tablaDatos.setValueAt(flag, i, 4);
            i++;
        }
    }
    
    public void agregarCuotas(Object[][] data) throws ParseException{
        int i = 0;
        for(Object[] data1 : data){
            Date date = formatDate.parse(data1[1].toString());
            boolean flag = data1[3].toString().compareTo("Pagado") == 0;
            tablaDatos.setValueAt(data1[0], i, 0);
            tablaDatos.setValueAt(date, i, 1);
            tablaDatos.setValueAt(Integer.parseInt(data1[2].toString()), i, 2);
            tablaDatos.setValueAt(flag, i, 3);
            i++;
        }
    }
    
    public void agregarProductos(String id) throws ParseException{
        int i = 0;
        modelos2.modeloCompras compra = new modeloCompras();
        Object[][] data = compra.obtenerProductosPorId(id);
        detalles.setRowCount(data.length);
        for(Object[] data1 : data){
            boolean flag = data1[4].toString().compareTo("1") == 0;
            tablaDetalle.setValueAt(data1[0], i, 0);
            tablaDetalle.setValueAt(data1[1], i, 1);
            tablaDetalle.setValueAt(data1[2], i, 2);
            tablaDetalle.setValueAt(Integer.parseInt(data1[3].toString()), i, 3);
            tablaDetalle.setValueAt(flag, i, 4);
            i++;
        }
    }
    
    public void setId(String id){
        this.id = id;
    }
    
    public String getId(){
        return this.id;
    }
    
    public JTable getTablaDetalle(){
        return tablaDetalle;
    }
    
    public String getIva(int row){
        if(tablaDetalle.getValueAt(row, 4) == null || (Boolean)tablaDetalle.getValueAt(row, 4) == false){
            return "Sin";
        }else{
            return "Con";
        }
    }
    
    public void calTotales(){
        int tot = 0;
        int net = 0;
        int iva = 0;
        try{
            for(int i = 0; i < tablaDetalle.getRowCount(); i++){
                if(tablaDetalle.getValueAt(i, 4) == Boolean.FALSE){
                    int totParcial = Integer.valueOf(tablaDetalle.getValueAt(i, 2).toString()) * 
                            Integer.valueOf(tablaDetalle.getValueAt(i, 3).toString());
                    tot += totParcial;
                    net += totParcial;
                }else{
                    int ivaParcial = 0;
                    int totParcial = Integer.valueOf(tablaDetalle.getValueAt(i, 2).toString()) * 
                            Integer.valueOf(tablaDetalle.getValueAt(i, 3).toString());
                    double ivaFloat = totParcial * 0.19;
                    ivaParcial = (int)Math.round(ivaFloat);
                    tot += totParcial;
                    net += totParcial + ivaParcial;
                    iva += ivaParcial;
                }
            }
        }catch(NullPointerException e){
            
        }
        textoTot.setValue(tot);
        textoIva.setValue(iva);
        textoNeto.setValue(net);
    }
}
